import Mathlib.Topology.Separation.Basic
import Mathlib.Topology.Order
import Mathlib.Topology.Order.Basic
import Mathlib.Topology.MetricSpace.Basic
import FormalSystem.Semantics.TaskFrame

/-!
# Probe: the cone-neighbourhood topology `𝒩_F` and the cone-subbasis topology `𝒯_F`

Everything here is over a *bare* relation `R : W → D → W → Prop`, using the library's
`TaskFrame.cone` (`def:task-relation`, *Cone* clause) and the library's literal *Limit* shape.
No frame structure is needed; the hypotheses each theorem consumes are stated explicitly, so the
report can say exactly which frame conditions each direction uses.

Definitions:
* `coneTopology R` — the paper's `𝒯_F` (`def:task-topology`): `generateFrom` all cones.
* `nbhdTopology R` — `𝒩_F`: `O` open iff every `w ∈ O` has some cone `(w)_x ⊆ O` (`x > 0`).

Results (all sorry-free):
* `t1Space_nbhdTopology_iff_limit` — Limit (⊆ half) `↔` `𝒩_F` is T1, **no other hypothesis**.
* `coneTopology_le_nbhdTopology` — `𝒯_F` is finer than `𝒩_F`, given only `R w 0 w`.
* `t1Space_coneTopology_of_limit` — `app:topology-t1`, from Limit + `R w 0 w`; reflection is
  not consumed.
* `r0Space_nbhdTopology_of_limit`, `r0Space_coneTopology_of_limit` — `app:topology-r0`.
* `nbhdTopology_isClosed_iff` — the closed sets of `𝒩_F` are the sets closed under
  "arbitrarily short tasks".
* `continuous_nbhdTopology_of_history` — every history `D → W` is `𝒩_F`-continuous (order
  topology on `D`); `finalTopology_le_nbhdTopology` — hence `𝒩_F ⊆` the final topology.
* `nbhdTopology_eq_mkOfNhds`, `isBasis_cone`, `coneFilter_le_nhds`, `nbhdTopology_le_of_coneFilter_le_nhds`
  — what `𝒩_F` *is*: the finest topology in which every neighbourhood of `w` contains a cone at
  `w`; the cones at `w` form a filter base.
* `isOpen_cone_of_triangle`, `coneTopology_eq_nbhdTopology_of_triangle` — under a triangle
  condition (mixed-sign composition) the cones are `𝒩_F`-open and the two topologies coincide.
* `limit_of_t1Space_coneTopology` — the converse of `app:topology-t1` is recovered under
  "no one-way instantaneous pairs" (Q4).
-/

open Topology TopologicalSpace Set Filter

set_option warn.classDefReducibility false

namespace FormalSystem.Semantics.TaskFrame

variable {D : Type} [AddCommGroup D] [LinearOrder D] [IsOrderedAddMonoid D] [Nontrivial D]
variable {W : Type}

/-- A nontrivial linearly ordered additive group has a positive element. -/
theorem exists_pos_duration : ∃ x : D, 0 < x := by
  obtain ⟨a, ha⟩ := exists_ne (0 : D)
  rcases lt_or_gt_of_ne ha with hlt | hgt
  · exact ⟨-a, neg_pos.mpr hlt⟩
  · exact ⟨a, hgt⟩

/-- The paper's *Limit* axiom (`def:frame#Limit`), ⊆ half, in the library's literal shape:
`⋂_{x > 0} (w)_x ⊆ {w}`. This is exactly the type of `FrameOver.limit`. -/
def Limit (R : W → D → W → Prop) : Prop :=
  ∀ w u, (∀ x, 0 < x → ∃ y, |y| < x ∧ R w y u) → u = w

omit [Nontrivial D] in
/-- With `R w 0 w`, every positive cone at `w` contains `w` — the ⊇ half of *Limit*. -/
theorem mem_cone_self {R : W → D → W → Prop} {w : W} (h0 : R w 0 w) {x : D} (hx : 0 < x) :
    w ∈ cone R w x :=
  ⟨0, by rw [abs_zero]; exact hx, h0⟩

/-! ## The two topologies -/

/-- `𝒯_F` (`def:task-topology`): the topology generated by all cones `(w)_x`, `x > 0`, as a
subbasis — "the result of closing `B_F` under arbitrary union and finite intersection". -/
def coneTopology (R : W → D → W → Prop) : TopologicalSpace W :=
  generateFrom {s | ∃ w x, 0 < x ∧ s = cone R w x}

/-- `𝒩_F`: `O` is open iff every `w ∈ O` has some cone `(w)_x ⊆ O` with `x > 0`. -/
def nbhdTopology (R : W → D → W → Prop) : TopologicalSpace W where
  IsOpen O := ∀ w ∈ O, ∃ x, 0 < x ∧ cone R w x ⊆ O
  isOpen_univ := fun _ _ =>
    let ⟨x, hx⟩ := exists_pos_duration (D := D); ⟨x, hx, subset_univ _⟩
  isOpen_inter := fun _ _ h₁ h₂ w hw => by
    obtain ⟨x₁, hx₁, hc₁⟩ := h₁ w hw.1
    obtain ⟨x₂, hx₂, hc₂⟩ := h₂ w hw.2
    exact ⟨min x₁ x₂, lt_min hx₁ hx₂,
      subset_inter ((cone_mono R w (min_le_left _ _)).trans hc₁)
        ((cone_mono R w (min_le_right _ _)).trans hc₂)⟩
  isOpen_sUnion := fun S hS w hw => by
    obtain ⟨O, hO, hwO⟩ := mem_sUnion.mp hw
    obtain ⟨x, hx, hc⟩ := hS O hO w hwO
    exact ⟨x, hx, hc.trans (subset_sUnion_of_mem hO)⟩

theorem nbhdTopology_isOpen_iff (R : W → D → W → Prop) {O : Set W} :
    IsOpen[nbhdTopology R] O ↔ ∀ w ∈ O, ∃ x, 0 < x ∧ cone R w x ⊆ O :=
  Iff.rfl

/-- The closed sets of `𝒩_F` are exactly the sets closed under arbitrarily short tasks: if `w`
reaches `C` within every positive radius, then `w ∈ C`. -/
theorem nbhdTopology_isClosed_iff (R : W → D → W → Prop) (C : Set W) :
    IsClosed[nbhdTopology R] C ↔
      ∀ w, (∀ x, 0 < x → (cone R w x ∩ C).Nonempty) → w ∈ C := by
  letI := nbhdTopology R
  rw [← isOpen_compl_iff, nbhdTopology_isOpen_iff]
  constructor
  · intro h w hw
    by_contra hwC
    obtain ⟨x, hx, hc⟩ := h w hwC
    obtain ⟨u, hu, huC⟩ := hw x hx
    exact hc hu huC
  · intro h w hw
    by_contra hne
    push Not at hne
    apply hw
    apply h
    intro x hx
    obtain ⟨u, hu, huC⟩ := Set.not_subset.mp (hne x hx)
    exact ⟨u, hu, by simpa using huC⟩

/-- **`𝒩_F` is discrete iff every state has a dwell time**: some `x > 0` with `(w)_x = {w}`
(here `(w)_x ⊆ {w}`; equality follows under `R w 0 w`). A *uniform* dwell time over dense
Archimedean `D` forces the static frame; the pointwise condition here does not. -/
theorem discreteTopology_nbhdTopology_iff (R : W → D → W → Prop) :
    @DiscreteTopology W (nbhdTopology R) ↔ ∀ w, ∃ x, 0 < x ∧ cone R w x ⊆ {w} := by
  letI := nbhdTopology R
  rw [discreteTopology_iff_isOpen_singleton]
  simp only [nbhdTopology_isOpen_iff, Set.mem_singleton_iff, forall_eq]

/-! ## Q1: Limit ↔ `𝒩_F` is T1, and `𝒯_F` is finer than `𝒩_F` -/

/-- **Limit (⊆ half) ↔ `𝒩_F` is T1.** No other frame condition is consumed in either
direction; `[Nontrivial D]` is used only so that `𝒩_F` is a topology at all. -/
theorem t1Space_nbhdTopology_iff_limit (R : W → D → W → Prop) :
    @T1Space W (nbhdTopology R) ↔ Limit R := by
  letI := nbhdTopology R
  constructor
  · intro h w u hwu
    haveI := h
    by_contra hne
    have hopen : IsOpen ({u}ᶜ : Set W) := isOpen_compl_singleton
    obtain ⟨x, hx, hc⟩ := hopen w (fun h => hne (Set.mem_singleton_iff.mp h).symm)
    exact hc (hwu x hx) rfl
  · intro hlim
    refine ⟨fun u => ?_⟩
    rw [← isOpen_compl_iff]
    intro w hw
    have hnot : ¬ ∀ x, 0 < x → ∃ y, |y| < x ∧ R w y u :=
      fun hh => hw (Set.mem_singleton_iff.mpr (hlim w u hh).symm)
    push Not at hnot
    obtain ⟨x, hx, hnx⟩ := hnot
    refine ⟨x, hx, fun v hv hvu => ?_⟩
    obtain ⟨y, hy, hR⟩ := hv
    rw [Set.mem_singleton_iff] at hvu
    subst hvu
    exact hnx y hy hR


/-! ## PROBE 656: the state-topology instance on the GENERAL frame -/

section Probe656

variable {D : TemporalOrder}

/-- The GENERAL fibre: `WorldState`, its nonemptiness, `PosRel`. No axiom fields. -/
structure PreFrame (D : TemporalOrder) where
  WorldState : Type
  [worldNonempty : Nonempty WorldState]
  PosRel : WorldState → D.PositiveCone → WorldState → Prop

attribute [instance] PreFrame.worldNonempty

namespace PreFrame

def TaskRel (F : PreFrame D) : F.WorldState → ↑D → F.WorldState → Prop :=
  FormalSystem.Semantics.TaskFrame.reflect F.PosRel

class IsRegular (F : PreFrame D) : Prop where
  serial : Serial F.TaskRel
  limit : Limit F.TaskRel

theorem limit (F : PreFrame D) [h : F.IsRegular] : Limit F.TaskRel := h.limit

/-- **The user-ratified instance**: `𝒩_F` on the GENERAL frame's state space. -/
instance stateTopology (F : PreFrame D) : TopologicalSpace F.WorldState :=
  nbhdTopology F.TaskRel

/-- `Limit` iff the state space is T1 -- on the GENERAL frame. -/
theorem t1Space_iff_limit (F : PreFrame D) : T1Space F.WorldState ↔ Limit F.TaskRel :=
  t1Space_nbhdTopology_iff_limit F.TaskRel

/-- Derived instance on the constrained class. -/
instance instT1 (F : PreFrame D) [F.IsRegular] : T1Space F.WorldState :=
  (t1Space_iff_limit F).mpr F.limit

/-- R0 comes free from Mathlib's `T1Space -> R0Space`. -/
example (F : PreFrame D) [F.IsRegular] : R0Space F.WorldState := inferInstance

/-- `𝒯_F` stays a plain `def` with NO instance, so there is exactly one `TopologicalSpace`
on a state space. -/
def coneTop (F : PreFrame D) : TopologicalSpace F.WorldState := coneTopology F.TaskRel

end PreFrame

/-! ### Keying / diamond probe at a frame whose carrier is `ℝ` -/

noncomputable abbrev realOrd : TemporalOrder := TemporalOrder.of Real

noncomputable def metricFrame : PreFrame realOrd where
  WorldState := Real
  PosRel := fun r x s => |s - r| ≤ (x : Real)

-- Mathlib's topology on `ℝ` is untouched: our instance is keyed on `PreFrame.WorldState _`.
noncomputable example : TopologicalSpace Real := inferInstance
-- At the projection form the frame instance is what synthesis returns.
noncomputable example : TopologicalSpace metricFrame.WorldState :=
  PreFrame.stateTopology metricFrame

/-- The projection is NOT reducibly `ℝ` for instance search: the two instances coexist.
This is the hazard to manage, not a contradiction. -/
example : (inferInstance : TopologicalSpace metricFrame.WorldState) =
    PreFrame.stateTopology metricFrame := rfl

#print axioms PreFrame.t1Space_iff_limit
#print axioms PreFrame.instT1

end Probe656

end FormalSystem.Semantics.TaskFrame
