/-
VERIFIED PROTOTYPE for the ultrafilter on the index type.

Checked with `lean_run_code` against the live tree on 2026-08-31; `eventually_mem` reports
axioms [propext, Classical.choice, Quot.sound]. Stated generically over `α : Type u`; the
implementation instantiates `α := FormalSystem.Syntax.Formula`.

No `Filter.atTop`, no `Preorder` instance on the subtype, no `Mathlib.Order.Filter.AtTopBot`
import: the filter is hand-built from its up-set basis in 16 lines.
-/

import Mathlib.Order.Filter.Ultrafilter.Basic

open Filter

universe u
variable {α : Type u}

/-- Index type: the finite sublists of `Γ`. -/
abbrev Idx (Γ : Set α) := {L : List α // ∀ ψ ∈ L, ψ ∈ Γ}

/-- The "tail" filter on the index type: generated by the up-sets of sublist inclusion. -/
def tailFilter (Γ : Set α) : Filter (Idx Γ) where
  sets := {s | ∃ L : Idx Γ, {L' : Idx Γ | ∀ ψ ∈ L.val, ψ ∈ L'.val} ⊆ s}
  univ_sets := ⟨⟨[], by simp⟩, fun _ _ => trivial⟩
  sets_of_superset := by
    rintro s t ⟨L, hL⟩ hst
    exact ⟨L, hL.trans hst⟩
  inter_sets := by
    rintro s t ⟨L1, h1⟩ ⟨L2, h2⟩
    refine ⟨⟨L1.val ++ L2.val, ?_⟩, ?_⟩
    · intro ψ hψ
      rcases List.mem_append.mp hψ with h | h
      · exact L1.property ψ h
      · exact L2.property ψ h
    · intro L' hL'
      simp only [Set.mem_setOf_eq, List.mem_append] at hL'
      exact ⟨h1 (fun ψ hψ => hL' ψ (Or.inl hψ)), h2 (fun ψ hψ => hL' ψ (Or.inr hψ))⟩

theorem mem_tailFilter {Γ : Set α} {s : Set (Idx Γ)} :
    s ∈ tailFilter Γ ↔ ∃ L : Idx Γ, {L' : Idx Γ | ∀ ψ ∈ L.val, ψ ∈ L'.val} ⊆ s := Iff.rfl

instance tailFilter_neBot (Γ : Set α) : (tailFilter Γ).NeBot := by
  constructor
  intro h
  have hmem : (∅ : Set (Idx Γ)) ∈ tailFilter Γ := by rw [h]; exact Filter.mem_bot
  obtain ⟨L, hL⟩ := mem_tailFilter.mp hmem
  exact hL (fun _ h => h)

/-- The ultrafilter on the index type. -/
noncomputable def idxUF (Γ : Set α) : Ultrafilter (Idx Γ) := Ultrafilter.of (tailFilter Γ)

/-- **The key property**: every member of `Γ` is eventually in the index list. This is what
makes each `ψ ∈ Γ` eventually true at the per-index witness, hence true in the ultraproduct. -/
theorem eventually_mem (Γ : Set α) {ψ : α} (hψ : ψ ∈ Γ) :
    ∀ᶠ L in (idxUF Γ : Filter (Idx Γ)), ψ ∈ L.val := by
  refine Ultrafilter.of_le (tailFilter Γ) ?_
  refine mem_tailFilter.mpr ⟨⟨[ψ], by simpa using hψ⟩, ?_⟩
  intro L' hL'
  exact hL' ψ (by simp)

#print axioms eventually_mem
