/-
Copyright (c) 2026 Benjamin Brast-McKie. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Benjamin Brast-McKie
-/

import FormalSystem.Semantics.IntNormalForm

/-!
# Sliced ℤ-frames: an infinite carrier with finite fibres

`FrameOver.ofStep` (`Semantics/IntNormalForm.lean`) synthesizes a `FrameOver intOrder` from a
bi-serial one-step relation on a **finite** carrier. This module synthesizes one from a
**time-indexed** one-step relation `R : ℤ → W → W → Prop` on the carrier `ℤ × W`: infinite, with
finite fibres.

## Why `ofStep` is not the route

`FrameOver.ofStep` requires `[Finite W]` on the whole carrier, and that requirement is not a
technicality of its proof — it is what its *Saturation* discharge
(`TaskFrame.saturation_of_finite`) consumes. A finite carrier is a genuine restriction on which
formulas a presented frame can refute: there is a `⊡`-free ℤ-time non-validity that **no**
frame built by `ofStep` satisfies at any finite carrier, while the landed `Formula`-side witness
family already certifies it. So a certificate class that presents its frame through `ofStep`
cannot be complete even on the `⊡`-free fragment, and the fix is to slice the carrier by time
rather than to enlarge a finite one.

`IntNormalForm.lean` is **not** modified by this module. Everything here is new: the time-indexed
iterate `iterS`, the two-sided relation `ofSlicedStepRel`, and the frame `FrameOver.ofSlicedStep`
built from them.

## The *Saturation* discharge is the whole point

`TaskFrame.saturation_of_fib_finite` needs only that each **fibre** is finite, which an infinite
carrier can satisfy, and its docstring names exactly this case. Here a fibre
`Fib (ofSlicedStepRel R) (t, w) d` is contained in `{t + d} ×ˢ Set.univ`, because the relation
pins the time component of its target: a `d`-step transition from slice `t` lands in slice
`t + d`, always. So the fibre injects into `W`, which is finite, while `ℤ × W` is not.

*Limit* is `TaskFrame.limit_of_succOrder` at the zero-duration law, exactly as for `ofStep`, and
*Compositionality* and the reflection law are the time-indexed twins of `iter_add` and
`ofStepRel`'s sign-guarded symmetry.

## Main definitions

- `iterS` — the time-indexed iterate: `iterS R n t w u` is an `n`-step `R`-path from `w` at
  slice `t` to `u` at slice `t + n`
- `ofSlicedStepRel` — the two-sided ℤ task relation on `ℤ × W` generated by `R`
- `FrameOver.ofSlicedStep` — the synthesized frame, with its three frame laws as named lemmas
- `IsSlicedStepPath` — an **offset** step path: a state sequence stepping along `R` at the
  shifted slice times
- `FrameOver.ofSlicedStep_mem_HF_iff` — the history space of the synthesized frame is exactly the
  set of offset step paths, in both directions

## Tags

task-frame · int-frame · sliced-carrier · saturation · finite-fibres
-/

namespace FormalSystem.Semantics

open TaskFrame

/-! ## The time-indexed iterate -/

/--
`iterS R n t w u`: an `n`-step `R`-path running from `w` at slice `t` to `u` at slice `t + n`.

The recursion appends the new step on the **right**, matching `iter`'s convention, which is what
makes `iterS_add` a direct induction on the second summand. The step taken at stage `i` is read at
slice `t + i`, so the slice index advances with the path.
-/
def iterS {W : Type} (R : ℤ → W → W → Prop) : ℕ → ℤ → W → W → Prop
  | 0, _, w, u => w = u
  | n + 1, t, w, u => ∃ v, iterS R n t w v ∧ R (t + n) v u

@[simp]
theorem iterS_zero {W : Type} (R : ℤ → W → W → Prop) (t : ℤ) (w u : W) :
    iterS R 0 t w u ↔ w = u := Iff.rfl

@[simp]
theorem iterS_succ {W : Type} (R : ℤ → W → W → Prop) (n : ℕ) (t : ℤ) (w u : W) :
    iterS R (n + 1) t w u ↔ ∃ v, iterS R n t w v ∧ R (t + n) v u := Iff.rfl

/-- One step is one edge, read at the path's own slice. -/
theorem iterS_one {W : Type} (R : ℤ → W → W → Prop) (t : ℤ) (w u : W) :
    iterS R 1 t w u ↔ R t w u := by
  constructor
  · rintro ⟨v, rfl, h⟩; simpa using h
  · intro h; exact ⟨w, rfl, by simpa using h⟩

/--
**Iteration adds**, with the slice index carried: an `(m + n)`-step path from slice `t` factors at
the `m`-th state, which sits at slice `t + m`.

This is the whole of *Compositionality* for the sliced normal form, and it is where the time index
does its work: the second factor starts at `t + m`, not at `t`.
-/
theorem iterS_add {W : Type} (R : ℤ → W → W → Prop) (m n : ℕ) (t : ℤ) (w u : W) :
    iterS R (m + n) t w u ↔ ∃ v, iterS R m t w v ∧ iterS R n (t + m) v u := by
  induction n generalizing u with
  | zero => simp
  | succ n ih =>
    -- `hcast` is oriented so that its left-hand side is the syntactic form the goal carries; the
    -- remaining gap (`↑(m + n)` against `↑(m.add n)`) is definitional and closed by `exact`.
    have hcast : (t + (m : ℤ)) + (n : ℤ) = t + ((m + n : ℕ) : ℤ) := by push_cast; omega
    constructor
    · rintro ⟨z, hz, hstep⟩
      obtain ⟨v, hv, hvz⟩ := (ih z).mp hz
      refine ⟨v, hv, z, hvz, ?_⟩
      rw [hcast]
      exact hstep
    · rintro ⟨v, hv, z, hvz, hstep⟩
      refine ⟨z, (ih z).mpr ⟨v, hv, hvz⟩, ?_⟩
      rw [hcast] at hstep
      exact hstep

/-- Forward seriality iterates: from every state at every slice there is an `n`-step forward
path. -/
theorem exists_iterS_fwd {W : Type} {R : ℤ → W → W → Prop} (fwd : ∀ t w, ∃ u, R t w u)
    (n : ℕ) (t : ℤ) (w : W) : ∃ u, iterS R n t w u := by
  induction n with
  | zero => exact ⟨w, rfl⟩
  | succ n ih =>
    obtain ⟨v, hv⟩ := ih
    obtain ⟨u, hu⟩ := fwd (t + n) v
    exact ⟨u, v, hv, hu⟩

/--
Backward seriality iterates: into every state at every slice there is an `n`-step forward path
**arriving** there, and it starts `n` slices earlier.
-/
theorem exists_iterS_bwd {W : Type} {R : ℤ → W → W → Prop} (bwd : ∀ t w, ∃ v, R (t - 1) v w)
    (n : ℕ) (t : ℤ) (u : W) : ∃ w, iterS R n (t - n) w u := by
  induction n generalizing t u with
  | zero => exact ⟨u, rfl⟩
  | succ n ih =>
    obtain ⟨v, hv⟩ := bwd t u
    obtain ⟨w, hw⟩ := ih (t - 1) v
    refine ⟨w, v, ?_, ?_⟩
    · have e : (t - 1) - (n : ℤ) = t - ((n + 1 : ℕ) : ℤ) := by push_cast; omega
      rwa [e] at hw
    · have e : (t - ((n + 1 : ℕ) : ℤ)) + (n : ℤ) = t - 1 := by push_cast; omega
      rwa [e]

/-! ## The two-sided relation on `ℤ × W` -/

/--
The two-sided ℤ task relation on `ℤ × W` generated by a time-indexed one-step relation `R`.

Three conjuncts: the **time component is pinned** (`q.1 = p.1 + d`, which is what makes the fibres
finite), and then the sign-guarded pair `ofStepRel` already uses, read through `iterS` at the
source slice of whichever direction is travelling forwards.
-/
def ofSlicedStepRel {W : Type} (R : ℤ → W → W → Prop) (p : ℤ × W) (d : ℤ) (q : ℤ × W) : Prop :=
  q.1 = p.1 + d ∧ (0 ≤ d → iterS R d.natAbs p.1 p.2 q.2) ∧ (d ≤ 0 → iterS R d.natAbs q.1 q.2 p.2)

/-- At a nonnegative duration, the relation is forward iteration plus the time equation. The
reverse conjunct is not lost: it can only fire at `d = 0`, where it follows from the forward one. -/
theorem ofSlicedStepRel_of_nonneg {W : Type} {R : ℤ → W → W → Prop} {d : ℤ} (hd : 0 ≤ d)
    (p q : ℤ × W) :
    ofSlicedStepRel R p d q ↔ q.1 = p.1 + d ∧ iterS R d.natAbs p.1 p.2 q.2 := by
  refine ⟨fun h => ⟨h.1, h.2.1 hd⟩, fun h => ⟨h.1, fun _ => h.2, fun hd' => ?_⟩⟩
  have hz : d = 0 := le_antisymm hd' hd
  subst hz
  simpa using (by simpa using h.2 : p.2 = q.2).symm

/-- At a nonpositive duration, the relation is backward iteration plus the time equation, by the
same argument mirrored. -/
theorem ofSlicedStepRel_of_nonpos {W : Type} {R : ℤ → W → W → Prop} {d : ℤ} (hd : d ≤ 0)
    (p q : ℤ × W) :
    ofSlicedStepRel R p d q ↔ q.1 = p.1 + d ∧ iterS R d.natAbs q.1 q.2 p.2 := by
  refine ⟨fun h => ⟨h.1, h.2.2 hd⟩, fun h => ⟨h.1, fun hd' => ?_, fun _ => h.2⟩⟩
  have hz : d = 0 := le_antisymm hd hd'
  subst hz
  simpa using (by simpa using h.2 : q.2 = p.2).symm

/-! ## The three frame laws, as named lemmas

Each is stated separately so that later phases cite a lemma rather than re-deriving it from the
frame's construction.
-/

/-- **The reflection law.** `ofSlicedStepRel` is symmetric in its two sign-guarded conjuncts by
construction, and the time equation `q.1 = p.1 + d` is `p.1 = q.1 + (-d)`. -/
theorem ofSlicedStepRel_reflect {W : Type} (R : ℤ → W → W → Prop) (p : ℤ × W) (d : ℤ)
    (q : ℤ × W) : ofSlicedStepRel R p d q ↔ ofSlicedStepRel R q (-d) p := by
  simp only [ofSlicedStepRel, Int.natAbs_neg]
  constructor
  · rintro ⟨h1, h2, h3⟩
    exact ⟨by omega, fun hd => h3 (by omega), fun hd => h2 (by omega)⟩
  · rintro ⟨h1, h2, h3⟩
    exact ⟨by omega, fun hd => h3 (by omega), fun hd => h2 (by omega)⟩

/-- **Compositionality**, both directions at once, from `iterS_add`. The interpolating state sits
at slice `p.1 + x`, which is what the time index in `iterS_add`'s second factor supplies. -/
theorem ofSlicedStep_compositional {W : Type} (R : ℤ → W → W → Prop) :
    TaskFrame.Compositional (ofSlicedStepRel R) := by
  rintro ⟨t, a⟩ ⟨s, b⟩ x y hx hy
  have hnat : (x + y).natAbs = x.natAbs + y.natAbs := by omega
  rw [ofSlicedStepRel_of_nonneg (add_nonneg hx hy)]
  constructor
  · rintro ⟨h1, h2⟩
    simp only at h1 h2
    rw [hnat, iterS_add] at h2
    obtain ⟨u, hu1, hu2⟩ := h2
    refine ⟨(t + x, u), (ofSlicedStepRel_of_nonneg hx _ _).mpr ⟨rfl, hu1⟩,
      (ofSlicedStepRel_of_nonneg hy _ _).mpr ⟨by simp only; omega, ?_⟩⟩
    have e : t + ((x.natAbs : ℤ)) = t + x := by omega
    rwa [e] at hu2
  · rintro ⟨⟨r, u⟩, hpu, huq⟩
    rw [ofSlicedStepRel_of_nonneg hx] at hpu
    rw [ofSlicedStepRel_of_nonneg hy] at huq
    obtain ⟨hr, hiu⟩ := hpu
    obtain ⟨hs, hiv⟩ := huq
    simp only at hr hs hiu hiv
    refine ⟨by simp only; omega, ?_⟩
    rw [hnat, iterS_add]
    refine ⟨u, hiu, ?_⟩
    have e : t + ((x.natAbs : ℤ)) = r := by omega
    rwa [e]

/-- **Seriality**, the one genuine obligation, from the two iterated seriality lemmas. -/
theorem ofSlicedStep_serial {W : Type} (R : ℤ → W → W → Prop)
    (fwd : ∀ t w, ∃ u, R t w u) (bwd : ∀ t w, ∃ v, R (t - 1) v w) :
    TaskFrame.Serial (ofSlicedStepRel R) := by
  rintro ⟨t, a⟩ x hx
  constructor
  · obtain ⟨u, hu⟩ := exists_iterS_fwd fwd x.natAbs t a
    exact ⟨(t + x, u), (ofSlicedStepRel_of_nonneg hx _ _).mpr ⟨rfl, hu⟩⟩
  · obtain ⟨v, hv⟩ := exists_iterS_bwd bwd x.natAbs t a
    refine ⟨(t - x, v), (ofSlicedStepRel_of_nonneg hx _ _).mpr ⟨by simp only; omega, ?_⟩⟩
    have e : ((x.natAbs : ℤ)) = x := Int.natAbs_of_nonneg hx
    simp only
    rwa [e] at hv

/-- **Limit**, by `TaskFrame.limit_of_succOrder` at the zero-duration law: a zero-duration
transition pins both components. -/
theorem ofSlicedStep_limit {W : Type} (R : ℤ → W → W → Prop) :
    TaskFrame.Limit (ofSlicedStepRel R) := by
  refine TaskFrame.limit_of_succOrder ?_
  rintro ⟨t, a⟩ ⟨s, b⟩ ⟨h1, h2, -⟩
  simp only at h1 h2
  have hab : a = b := by simpa using h2 (le_refl (0 : ℤ))
  have hts : s = t := by omega
  subst hts; subst hab; rfl

/--
**Finite fibres.** The relation pins the time component of its target, so a fibre is contained in
a single slice and injects into `W`.

This is what `TaskFrame.saturation_of_fib_finite` consumes, and it is the reason the carrier may be
infinite: `ℤ × W` is not finite, but every fibre of it is.
-/
theorem ofSlicedStep_fib_finite {W : Type} [Finite W] (R : ℤ → W → W → Prop) :
    ∀ (p : ℤ × W) (d : ℤ), (TaskFrame.Fib (ofSlicedStepRel R) p d).Finite := by
  intro p d
  refine Set.Finite.subset ((Set.finite_singleton (p.1 + d)).prod Set.finite_univ) ?_
  intro q hq
  exact ⟨hq.1, Set.mem_univ _⟩

/-- **Saturation**, from finite fibres alone. -/
theorem ofSlicedStep_saturation {W : Type} [Finite W] (R : ℤ → W → W → Prop) :
    TaskFrame.Saturation (ofSlicedStepRel R) :=
  TaskFrame.saturation_of_fib_finite (ofSlicedStep_fib_finite R)

/-! ## The synthesized frame -/

namespace FrameOver

/--
**Frame synthesis over a sliced carrier**: a bi-serial time-indexed relation on a finite nonempty
`W` generates a `FrameOver intOrder` on the **infinite** carrier `ℤ × W`.

Field discharges, each a named lemma above: reflection `ofSlicedStepRel_reflect`,
*Compositionality* `ofSlicedStep_compositional`, *Seriality* `ofSlicedStep_serial`, *Limit*
`ofSlicedStep_limit`, *Saturation* `ofSlicedStep_saturation`.

This is **not** `FrameOver.ofStep` at a different carrier, and it is not reducible to it: `ofStep`
requires `[Finite W]` on the whole carrier, which is exactly what is given up here. See this
module's header for why that matters.
-/
def ofSlicedStep {W : Type} [Finite W] [Nonempty W] (R : ℤ → W → W → Prop)
    (fwd : ∀ t w, ∃ u, R t w u) (bwd : ∀ t w, ∃ v, R (t - 1) v w) : FrameOver intOrder :=
  FrameOver.ofReflectiveRegular (ℤ × W) (ofSlicedStepRel R)
    (fun p d q => ofSlicedStepRel_reflect R p d q)
    (ofSlicedStep_compositional R)
    (ofSlicedStep_serial R fwd bwd)
    (ofSlicedStep_limit R)
    (ofSlicedStep_saturation R)

/-- **`ofSlicedStep` is regular**, through the regular constructor's auto-instance. -/
instance ofSlicedStep_isRegular {W : Type} [Finite W] [Nonempty W] (R : ℤ → W → W → Prop)
    (fwd : ∀ t w, ∃ u, R t w u) (bwd : ∀ t w, ∃ v, R (t - 1) v w) :
    (ofSlicedStep R fwd bwd).IsRegular :=
  FrameOver.instIsRegularOfReflective _ _ _ _ _ _ _

@[simp]
theorem ofSlicedStep_taskRel {W : Type} [Finite W] [Nonempty W] (R : ℤ → W → W → Prop)
    (fwd : ∀ t w, ∃ u, R t w u) (bwd : ∀ t w, ∃ v, R (t - 1) v w) :
    (ofSlicedStep R fwd bwd).TaskRel = ofSlicedStepRel R :=
  FrameOver.ofReflectiveRegular_taskRel_eq

/-- The one-step relation of the synthesized frame advances the slice by one and steps along `R`. -/
theorem ofSlicedStep_step {W : Type} [Finite W] [Nonempty W] (R : ℤ → W → W → Prop)
    (fwd : ∀ t w, ∃ u, R t w u) (bwd : ∀ t w, ∃ v, R (t - 1) v w) (p q : ℤ × W) :
    (ofSlicedStep R fwd bwd).step p q ↔ q.1 = p.1 + 1 ∧ R p.1 p.2 q.2 := by
  change (ofSlicedStep R fwd bwd).TaskRel p 1 q ↔ _
  rw [ofSlicedStep_taskRel, ofSlicedStepRel_of_nonneg (zero_le_one : (0 : ℤ) ≤ 1)]
  simp only [Int.natAbs_one, iterS_one]

/-! ### The carrier is infinite, and that is proved rather than asserted -/

instance ofSlicedStep_worldState_infinite {W : Type} [Finite W] [Nonempty W]
    (R : ℤ → W → W → Prop) (fwd : ∀ t w, ∃ u, R t w u) (bwd : ∀ t w, ∃ v, R (t - 1) v w) :
    Infinite (ofSlicedStep R fwd bwd).WorldState :=
  inferInstanceAs (Infinite (ℤ × W))

/--
**The synthesized frame's carrier is not finite.** This is the amendment cashed out: the whole
reason this module exists rather than a call to `FrameOver.ofStep`.
-/
theorem ofSlicedStep_not_finite_worldState {W : Type} [Finite W] [Nonempty W]
    (R : ℤ → W → W → Prop) (fwd : ∀ t w, ∃ u, R t w u) (bwd : ∀ t w, ∃ v, R (t - 1) v w) :
    ¬ Finite (ofSlicedStep R fwd bwd).WorldState :=
  not_finite_iff_infinite.mpr (ofSlicedStep_worldState_infinite R fwd bwd)

end FrameOver

/-! ## The history space: exactly the offset step paths -/

/--
An **offset step path**: a state sequence `g` stepping along `R` read at the slice times shifted by
a fixed offset `k`.

The offset is what replaces an absolute origin. A history of the synthesized frame occupies slice
`t + k` at time `t`, for a `k` it fixes once; nothing is aligned, and there is no period to
compute.
-/
def IsSlicedStepPath {W : Type} (R : ℤ → W → W → Prop) (k : ℤ) (g : ℤ → W) : Prop :=
  ∀ t : ℤ, R (t + k) (g t) (g (t + 1))

namespace FrameOver

/--
**The history space of `ofSlicedStep` is exactly the set of offset step paths.**

Both directions are stated and both are load bearing: the `←` direction builds a history from a
labelled path, and the `→` direction says a history has no freedom beyond its offset — which is
what lets a universal condition over histories be read as a condition on one slice.

Routed through `FrameOver.mem_HF_iff_adjacent`: over ℤ a history is exactly a bi-infinite step
path, and a step of this frame advances the slice by one, so the time component is forced to be
`t + k` with `k` the slice occupied at time `0`.
-/
theorem ofSlicedStep_mem_HF_iff {W : Type} [Finite W] [Nonempty W] (R : ℤ → W → W → Prop)
    (fwd : ∀ t w, ∃ u, R t w u) (bwd : ∀ t w, ∃ v, R (t - 1) v w) (f : ℤ → ℤ × W) :
    (∃ τ : WorldHistory (ofSlicedStep R fwd bwd), τ.path = f) ↔
      ∃ (k : ℤ) (g : ℤ → W), IsSlicedStepPath R k g ∧ f = fun t => (t + k, g t) := by
  refine Iff.trans (FrameOver.mem_HF_iff_adjacent (ofSlicedStep R fwd bwd) f) ?_
  constructor
  · intro hstep
    have hadj : ∀ n : ℤ, (f (n + 1)).1 = (f n).1 + 1 ∧ R (f n).1 (f n).2 (f (n + 1)).2 :=
      fun n => (ofSlicedStep_step R fwd bwd (f n) (f (n + 1))).mp (hstep n)
    have hfst : ∀ t : ℤ, (f t).1 = t + (f 0).1 := by
      intro t
      induction t using Int.induction_on with
      | zero => simp
      | succ n ih => have := (hadj (n : ℤ)).1; omega
      | pred n ih =>
        have h := (hadj (-(n : ℤ) - 1)).1
        rw [show (-(n : ℤ) - 1) + 1 = -(n : ℤ) by omega] at h
        omega
    refine ⟨(f 0).1, fun t => (f t).2, ?_, ?_⟩
    · intro t
      have h := (hadj t).2
      rwa [hfst t] at h
    · funext t
      have h1 : (f t).1 = t + (f 0).1 := hfst t
      exact Prod.ext h1 rfl
  · rintro ⟨k, g, hg, rfl⟩
    intro n
    refine (ofSlicedStep_step R fwd bwd _ _).mpr ⟨?_, ?_⟩
    · change (n + 1) + k = (n + k) + 1
      omega
    · exact hg n

end FrameOver

end FormalSystem.Semantics
