import Mathlib.Topology.Separation.Basic
import Mathlib.Topology.Order
import Mathlib.Topology.Order.Basic
import FormalSystem.Semantics.TaskFrame

/-!
# Probe: the cone-neighbourhood topology `𝒩_F` and the cone-subbasis topology `𝒯_F`

Everything here is over a *bare* relation `R : W → D → W → Prop`, using the library's
`TaskFrame.cone` (`def:task-relation`, *Cone* clause) and the library's literal *Limit* shape.
No frame structure is needed; the hypotheses each theorem consumes are stated explicitly, so the
report can say exactly which frame conditions each direction uses.

Definitions:
* `coneTopology R` — the paper's `𝒯_F` (`def:task-topology`): `generateFrom` all cones.
* `nbhdTopology R` — `𝒩_F`: `O` open iff every `w ∈ O` has some cone `(w)_x ⊆ O` (`x > 0`).

Results (all sorry-free):
* `t1Space_nbhdTopology_iff_limit` — Limit (⊆ half) `↔` `𝒩_F` is T1, **no other hypothesis**.
* `coneTopology_le_nbhdTopology` — `𝒯_F` is finer than `𝒩_F`, given only `R w 0 w`.
* `t1Space_coneTopology_of_limit` — `app:topology-t1`, from Limit + `R w 0 w`; reflection is
  not consumed.
* `r0Space_nbhdTopology_of_limit`, `r0Space_coneTopology_of_limit` — `app:topology-r0`.
* `nbhdTopology_isClosed_iff` — the closed sets of `𝒩_F` are the sets closed under
  "arbitrarily short tasks".
* `continuous_nbhdTopology_of_history` — every history `D → W` is `𝒩_F`-continuous (order
  topology on `D`); `finalTopology_le_nbhdTopology` — hence `𝒩_F ⊆` the final topology.
* `nbhdTopology_eq_mkOfNhds`, `isBasis_cone`, `coneFilter_le_nhds`, `nbhdTopology_le_of_coneFilter_le_nhds`
  — what `𝒩_F` *is*: the finest topology in which every neighbourhood of `w` contains a cone at
  `w`; the cones at `w` form a filter base.
* `isOpen_cone_of_triangle`, `coneTopology_eq_nbhdTopology_of_triangle` — under a triangle
  condition (mixed-sign composition) the cones are `𝒩_F`-open and the two topologies coincide.
* `limit_of_t1Space_coneTopology` — the converse of `app:topology-t1` is recovered under
  "no one-way instantaneous pairs" (Q4).
-/

open Topology TopologicalSpace Set Filter

set_option warn.classDefReducibility false

namespace FormalSystem.Semantics.TaskFrame

variable {D : Type} [AddCommGroup D] [LinearOrder D] [IsOrderedAddMonoid D] [Nontrivial D]
variable {W : Type}

/-- A nontrivial linearly ordered additive group has a positive element. -/
theorem exists_pos_duration : ∃ x : D, 0 < x := by
  obtain ⟨a, ha⟩ := exists_ne (0 : D)
  rcases lt_or_gt_of_ne ha with hlt | hgt
  · exact ⟨-a, neg_pos.mpr hlt⟩
  · exact ⟨a, hgt⟩

/-- The paper's *Limit* axiom (`def:frame#Limit`), ⊆ half, in the library's literal shape:
`⋂_{x > 0} (w)_x ⊆ {w}`. This is exactly the type of `FrameOver.limit`. -/
def Limit (R : W → D → W → Prop) : Prop :=
  ∀ w u, (∀ x, 0 < x → ∃ y, |y| < x ∧ R w y u) → u = w

omit [Nontrivial D] in
/-- With `R w 0 w`, every positive cone at `w` contains `w` — the ⊇ half of *Limit*. -/
theorem mem_cone_self {R : W → D → W → Prop} {w : W} (h0 : R w 0 w) {x : D} (hx : 0 < x) :
    w ∈ cone R w x :=
  ⟨0, by rw [abs_zero]; exact hx, h0⟩

/-! ## The two topologies -/

/-- `𝒯_F` (`def:task-topology`): the topology generated by all cones `(w)_x`, `x > 0`, as a
subbasis — "the result of closing `B_F` under arbitrary union and finite intersection". -/
def coneTopology (R : W → D → W → Prop) : TopologicalSpace W :=
  generateFrom {s | ∃ w x, 0 < x ∧ s = cone R w x}

/-- `𝒩_F`: `O` is open iff every `w ∈ O` has some cone `(w)_x ⊆ O` with `x > 0`. -/
def nbhdTopology (R : W → D → W → Prop) : TopologicalSpace W where
  IsOpen O := ∀ w ∈ O, ∃ x, 0 < x ∧ cone R w x ⊆ O
  isOpen_univ := fun _ _ =>
    let ⟨x, hx⟩ := exists_pos_duration (D := D); ⟨x, hx, subset_univ _⟩
  isOpen_inter := fun _ _ h₁ h₂ w hw => by
    obtain ⟨x₁, hx₁, hc₁⟩ := h₁ w hw.1
    obtain ⟨x₂, hx₂, hc₂⟩ := h₂ w hw.2
    exact ⟨min x₁ x₂, lt_min hx₁ hx₂,
      subset_inter ((cone_mono R w (min_le_left _ _)).trans hc₁)
        ((cone_mono R w (min_le_right _ _)).trans hc₂)⟩
  isOpen_sUnion := fun S hS w hw => by
    obtain ⟨O, hO, hwO⟩ := mem_sUnion.mp hw
    obtain ⟨x, hx, hc⟩ := hS O hO w hwO
    exact ⟨x, hx, hc.trans (subset_sUnion_of_mem hO)⟩

theorem nbhdTopology_isOpen_iff (R : W → D → W → Prop) {O : Set W} :
    IsOpen[nbhdTopology R] O ↔ ∀ w ∈ O, ∃ x, 0 < x ∧ cone R w x ⊆ O :=
  Iff.rfl

/-- The closed sets of `𝒩_F` are exactly the sets closed under arbitrarily short tasks: if `w`
reaches `C` within every positive radius, then `w ∈ C`. -/
theorem nbhdTopology_isClosed_iff (R : W → D → W → Prop) (C : Set W) :
    IsClosed[nbhdTopology R] C ↔
      ∀ w, (∀ x, 0 < x → (cone R w x ∩ C).Nonempty) → w ∈ C := by
  letI := nbhdTopology R
  rw [← isOpen_compl_iff, nbhdTopology_isOpen_iff]
  constructor
  · intro h w hw
    by_contra hwC
    obtain ⟨x, hx, hc⟩ := h w hwC
    obtain ⟨u, hu, huC⟩ := hw x hx
    exact hc hu huC
  · intro h w hw
    by_contra hne
    push Not at hne
    apply hw
    apply h
    intro x hx
    obtain ⟨u, hu, huC⟩ := Set.not_subset.mp (hne x hx)
    exact ⟨u, hu, by simpa using huC⟩

/-- **`𝒩_F` is discrete iff every state has a dwell time**: some `x > 0` with `(w)_x = {w}`
(here `(w)_x ⊆ {w}`; equality follows under `R w 0 w`). A *uniform* dwell time over dense
Archimedean `D` forces the static frame; the pointwise condition here does not. -/
theorem discreteTopology_nbhdTopology_iff (R : W → D → W → Prop) :
    @DiscreteTopology W (nbhdTopology R) ↔ ∀ w, ∃ x, 0 < x ∧ cone R w x ⊆ {w} := by
  letI := nbhdTopology R
  rw [discreteTopology_iff_isOpen_singleton]
  simp only [nbhdTopology_isOpen_iff, Set.mem_singleton_iff, forall_eq]

/-! ## Q1: Limit ↔ `𝒩_F` is T1, and `𝒯_F` is finer than `𝒩_F` -/

/-- **Limit (⊆ half) ↔ `𝒩_F` is T1.** No other frame condition is consumed in either
direction; `[Nontrivial D]` is used only so that `𝒩_F` is a topology at all. -/
theorem t1Space_nbhdTopology_iff_limit (R : W → D → W → Prop) :
    @T1Space W (nbhdTopology R) ↔ Limit R := by
  letI := nbhdTopology R
  constructor
  · intro h w u hwu
    haveI := h
    by_contra hne
    have hopen : IsOpen ({u}ᶜ : Set W) := isOpen_compl_singleton
    obtain ⟨x, hx, hc⟩ := hopen w (fun h => hne (Set.mem_singleton_iff.mp h).symm)
    exact hc (hwu x hx) rfl
  · intro hlim
    refine ⟨fun u => ?_⟩
    rw [← isOpen_compl_iff]
    intro w hw
    have hnot : ¬ ∀ x, 0 < x → ∃ y, |y| < x ∧ R w y u :=
      fun hh => hw (Set.mem_singleton_iff.mpr (hlim w u hh).symm)
    push Not at hnot
    obtain ⟨x, hx, hnx⟩ := hnot
    refine ⟨x, hx, fun v hv hvu => ?_⟩
    obtain ⟨y, hy, hR⟩ := hv
    rw [Set.mem_singleton_iff] at hvu
    subst hvu
    exact hnx y hy hR

/-- **`𝒯_F` is finer than `𝒩_F`** (in Mathlib's order, `coneTopology R ≤ nbhdTopology R`),
given only that every state loops at duration zero: an `𝒩_F`-open set is the union of the
cones it contains. This corrects the claim that the two topologies are incomparable. -/
theorem coneTopology_le_nbhdTopology (R : W → D → W → Prop) (h0 : ∀ w, R w 0 w) :
    coneTopology R ≤ nbhdTopology R := by
  rw [TopologicalSpace.le_def]
  intro O hO
  have hO' : O = ⋃₀ {c | (∃ w x, 0 < x ∧ c = cone R w x) ∧ c ⊆ O} := by
    ext v
    constructor
    · intro hv
      obtain ⟨x, hx, hc⟩ := hO v hv
      exact ⟨cone R v x, ⟨⟨v, x, hx, rfl⟩, hc⟩, mem_cone_self (h0 v) hx⟩
    · rintro ⟨c, ⟨_, hcO⟩, hvc⟩
      exact hcO hvc
  rw [hO']
  letI := coneTopology R
  exact isOpen_sUnion fun c hc => isOpen_generateFrom_of_mem hc.1

/-- **`app:topology-t1`**: `𝒯_F` is T1, from *Limit* and `R w 0 w`. The paper's proof also
consumes the reflection convention; this route does not, since T1 is inherited by finer
topologies and `𝒩_F` is already T1. -/
theorem t1Space_coneTopology_of_limit (R : W → D → W → Prop) (h0 : ∀ w, R w 0 w)
    (hlim : Limit R) : @T1Space W (coneTopology R) :=
  t1Space_antitone (coneTopology_le_nbhdTopology R h0)
    ((t1Space_nbhdTopology_iff_limit R).mpr hlim)

/-- `𝒩_F` is R0 under *Limit* (T1 implies R0). -/
theorem r0Space_nbhdTopology_of_limit (R : W → D → W → Prop) (hlim : Limit R) :
    @R0Space W (nbhdTopology R) := by
  letI := nbhdTopology R
  haveI := (t1Space_nbhdTopology_iff_limit R).mpr hlim
  infer_instance

/-- **`app:topology-r0`**: `𝒯_F` is R0 under *Limit* and `R w 0 w`. -/
theorem r0Space_coneTopology_of_limit (R : W → D → W → Prop) (h0 : ∀ w, R w 0 w)
    (hlim : Limit R) : @R0Space W (coneTopology R) := by
  letI := coneTopology R
  haveI := t1Space_coneTopology_of_limit R h0 hlim
  infer_instance

/-- The paper's equality form of *Limit*, `⋂_{x>0} (w)_x = {w}`, is equivalent to `𝒩_F` T1
together with the ⊇ half `w ∈ (w)_x`; the ⊇ half follows from `R w 0 w`. -/
theorem limit_eq_iff (R : W → D → W → Prop) :
    (∀ w, ⋂ x > (0 : D), cone R w x = {w}) ↔
      (@T1Space W (nbhdTopology R) ∧ ∀ w x, 0 < x → w ∈ cone R w x) := by
  rw [t1Space_nbhdTopology_iff_limit]
  constructor
  · intro h
    refine ⟨fun w u hu => ?_, fun w x hx => ?_⟩
    · have : u ∈ ⋂ x > (0 : D), cone R w x := by
        simp only [Set.mem_iInter]; exact fun x hx => hu x hx
      rw [h w] at this
      exact this
    · have : w ∈ ⋂ x > (0 : D), cone R w x := by rw [h w]; rfl
      simp only [Set.mem_iInter] at this
      exact this x hx
  · rintro ⟨hlim, hself⟩ w
    ext u
    simp only [Set.mem_iInter, Set.mem_singleton_iff]
    constructor
    · intro hu; exact hlim w u fun x hx => hu x hx
    · rintro rfl; exact fun x hx => hself u x hx

/-! ## Q2: what `𝒩_F` is — a neighbourhood system, the cones as a filter base -/

/-- The cone filter at `w`: sets containing some positive cone at `w`. -/
def coneFilter (R : W → D → W → Prop) (w : W) : Filter W :=
  ⨅ x ∈ {x : D | 0 < x}, 𝓟 (cone R w x)

/-- The cones at `w` form a filter base: they are nested in the radius. -/
theorem isBasis_cone (R : W → D → W → Prop) (w : W) :
    Filter.IsBasis (fun x : D => 0 < x) (fun x => cone R w x) :=
  ⟨exists_pos_duration, fun {x₁ x₂} hx₁ hx₂ =>
    ⟨min x₁ x₂, lt_min hx₁ hx₂,
      subset_inter (cone_mono R w (min_le_left _ _)) (cone_mono R w (min_le_right _ _))⟩⟩

theorem mem_coneFilter (R : W → D → W → Prop) (w : W) {s : Set W} :
    s ∈ coneFilter R w ↔ ∃ x, 0 < x ∧ cone R w x ⊆ s := by
  unfold coneFilter
  rw [Filter.mem_biInf_of_directed]
  · simp only [Set.mem_setOf_eq, Filter.mem_principal]
  · rintro x hx y hy
    exact ⟨min x y, lt_min hx hy, principal_mono.mpr (cone_mono R w (min_le_left _ _)),
      principal_mono.mpr (cone_mono R w (min_le_right _ _))⟩
  · exact let ⟨x, hx⟩ := exists_pos_duration (D := D); ⟨x, hx⟩

/-- `𝒩_F` is `TopologicalSpace.mkOfNhds` of the cone filters. -/
theorem nbhdTopology_eq_mkOfNhds (R : W → D → W → Prop) :
    nbhdTopology R = TopologicalSpace.mkOfNhds (coneFilter R) := by
  apply TopologicalSpace.ext
  funext O
  apply propext
  rw [nbhdTopology_isOpen_iff]
  change _ ↔ ∀ w ∈ O, O ∈ coneFilter R w
  simp only [mem_coneFilter]

/-- In `𝒩_F`, every neighbourhood of `w` contains a cone at `w`: `coneFilter R w ≤ 𝓝 w`. -/
theorem coneFilter_le_nhds (R : W → D → W → Prop) (w : W) :
    coneFilter R w ≤ @nhds W (nbhdTopology R) w := by
  letI := nbhdTopology R
  rw [le_nhds_iff]
  intro s hws hs
  rw [mem_coneFilter]
  exact hs w hws

/-- `𝒩_F` is the **finest** topology in which every neighbourhood of `w` contains a cone at `w`.
(Not "the finest in which cones are neighbourhoods" — that would be the discrete topology; and
the cones need not be `𝒩_F`-neighbourhoods at all, see `FourState.lean`.) -/
theorem nbhdTopology_le_of_coneFilter_le_nhds (R : W → D → W → Prop) (t : TopologicalSpace W)
    (h : ∀ w, coneFilter R w ≤ @nhds W t w) : nbhdTopology R ≤ t := by
  rw [TopologicalSpace.le_def]
  intro O hO w hw
  letI := t
  have := (h w) (hO.mem_nhds hw)
  rwa [mem_coneFilter] at this

/-! ## Q2: histories are `𝒩_F`-continuous; `𝒩_F` is below the final topology -/

/-- A (total) history over a bare relation: `def:world-history` with `X = D`. -/
def IsHistory (R : W → D → W → Prop) (τ : D → W) : Prop :=
  ∀ x y, R (τ x) (y - x) (τ y)

/-- **Every history is continuous** from the order topology on `D` to `𝒩_F` — unconditionally,
with no frame axiom consumed. -/
theorem continuous_nbhdTopology_of_history [TopologicalSpace D] [OrderTopology D]
    (R : W → D → W → Prop) {τ : D → W} (hτ : IsHistory R τ) :
    @Continuous D W _ (nbhdTopology R) τ := by
  letI := nbhdTopology R
  rw [continuous_def]
  intro O hO
  rw [isOpen_iff_forall_mem_open]
  intro z hz
  obtain ⟨x, hx, hc⟩ := hO (τ z) hz
  refine ⟨Set.Ioo (z - x) (z + x), fun y hy => hc ⟨y - z, ?_, hτ z y⟩, isOpen_Ioo,
    sub_lt_self z hx, lt_add_of_pos_right z hx⟩
  exact abs_sub_lt_iff.mpr ⟨sub_lt_iff_lt_add'.mpr hy.2, sub_lt_comm.mp hy.1⟩

/-- **`𝒩_F` is contained in the final topology** of all histories (order topology on `D`):
the final topology is finer, i.e. `⨆ coinduced ≤ nbhdTopology`. -/
theorem finalTopology_le_nbhdTopology [TopologicalSpace D] [OrderTopology D]
    (R : W → D → W → Prop) :
    (⨆ τ : {τ : D → W // IsHistory R τ}, coinduced τ.1 ‹TopologicalSpace D›) ≤
      nbhdTopology R :=
  iSup_le fun τ => continuous_iff_coinduced_le.mp (continuous_nbhdTopology_of_history R τ.2)

/-! ## Q2: when are the cones `𝒩_F`-open? The triangle (mixed-sign composition) condition -/

/-- A triangle condition: any two-step path can be shortcut by a single task no longer than
the sum. Same-sign composition gives it with `t = y + z`; what it adds is the mixed-sign case,
which `def:frame`'s *Compositionality* leaves inexpressible. Deterministic (group-action)
frames and the metric frames satisfy it. -/
def Triangle (R : W → D → W → Prop) : Prop :=
  ∀ w u v y z, R w y u → R u z v → ∃ t, |t| ≤ |y| + |z| ∧ R w t v

/-- Under the triangle condition every cone is `𝒩_F`-open. -/
theorem isOpen_cone_of_triangle {R : W → D → W → Prop} (hT : Triangle R) (w : W) (x : D) :
    IsOpen[nbhdTopology R] (cone R w x) := by
  rintro u ⟨y, hy, hR⟩
  refine ⟨x - |y|, sub_pos.mpr hy, ?_⟩
  rintro v ⟨z, hz, hR'⟩
  obtain ⟨t, ht, hRt⟩ := hT w u v y z hR hR'
  exact ⟨t, lt_of_le_of_lt ht (lt_sub_iff_add_lt'.mp hz), hRt⟩

/-- Under the triangle condition and `R w 0 w`, `𝒯_F = 𝒩_F`. -/
theorem coneTopology_eq_nbhdTopology_of_triangle {R : W → D → W → Prop} (h0 : ∀ w, R w 0 w)
    (hT : Triangle R) : coneTopology R = nbhdTopology R := by
  refine le_antisymm (coneTopology_le_nbhdTopology R h0) ?_
  rw [coneTopology, le_generateFrom_iff_subset_isOpen]
  rintro s ⟨w, x, _, rfl⟩
  exact isOpen_cone_of_triangle hT w x

/-- Conversely, if every cone is `𝒩_F`-open then `𝒩_F ≤ 𝒯_F`; with `R w 0 w` the two coincide
exactly when the cones are `𝒩_F`-open. -/
theorem coneTopology_eq_nbhdTopology_iff {R : W → D → W → Prop} (h0 : ∀ w, R w 0 w) :
    coneTopology R = nbhdTopology R ↔
      ∀ w x, 0 < x → IsOpen[nbhdTopology R] (cone R w x) := by
  constructor
  · intro h w x hx
    rw [← h]
    exact isOpen_generateFrom_of_mem ⟨w, x, hx, rfl⟩
  · intro h
    refine le_antisymm (coneTopology_le_nbhdTopology R h0) ?_
    rw [coneTopology, le_generateFrom_iff_subset_isOpen]
    rintro s ⟨w, x, hx, rfl⟩
    exact h w x hx

/-! ## Q4: the converse of `app:topology-t1` under "no one-way instantaneous pairs" -/

/-- `u` is forward-instantaneously reachable from `w`: `w ⇒_y u` for arbitrarily small `y ≥ 0`. -/
def QuickFwd (R : W → D → W → Prop) (w u : W) : Prop :=
  ∀ x, 0 < x → ∃ y, 0 ≤ y ∧ y < x ∧ R w y u

/-- No one-way instantaneous pairs: forward-instantaneous reachability is symmetric. -/
def NoOneWay (R : W → D → W → Prop) : Prop :=
  ∀ w u, QuickFwd R w u → QuickFwd R u w

omit [Nontrivial D] in
/-- **The gap between `𝒯_F`-T1 and Limit is exactly the one-way instantaneous pairs**: given
the reflection convention, the composition half of *Compositionality*, and *NoOneWay*, `𝒯_F`
being T1 implies *Limit*. (Contrapositively: every frame with `𝒯_F` T1 and *Limit* failing
contains a one-way instantaneous pair, as the four-state funnel does.) -/
theorem limit_of_t1Space_coneTopology {R : W → D → W → Prop}
    (hrefl : ∀ w d u, R w d u → R u (-d) w)
    (hcomp : ∀ w u v x y, 0 ≤ x → 0 ≤ y → R w x u → R u y v → R w (x + y) v)
    (hno : NoOneWay R) (hT1 : @T1Space W (coneTopology R)) : Limit R := by
  intro w u hwu
  -- Step 1: `w` and `u` are forward-instantaneous in at least one direction, hence in both.
  have hq : QuickFwd R w u ∨ QuickFwd R u w := by
    by_contra h
    rw [not_or] at h
    obtain ⟨h1, h2⟩ := h
    unfold QuickFwd at h1 h2
    push Not at h1 h2
    obtain ⟨x₀, hx₀, h1⟩ := h1
    obtain ⟨x₁, hx₁, h2⟩ := h2
    obtain ⟨y, hy, hR⟩ := hwu (min x₀ x₁) (lt_min hx₀ hx₁)
    rcases le_or_gt 0 y with hy0 | hy0
    · rw [abs_of_nonneg hy0] at hy
      exact h1 y hy0 (lt_of_lt_of_le hy (min_le_left _ _)) hR
    · rw [abs_of_neg hy0] at hy
      exact h2 (-y) (neg_nonneg.mpr hy0.le) (lt_of_lt_of_le hy (min_le_right _ _))
        (hrefl _ _ _ hR)
  have hq2 : QuickFwd R w u ∧ QuickFwd R u w := by
    rcases hq with h | h
    · exact ⟨h, hno w u h⟩
    · exact ⟨hno u w h, h⟩
  -- Step 2: every cone containing `w` contains `u`.
  have key : ∀ v x, 0 < x → w ∈ cone R v x → u ∈ cone R v x := by
    rintro v x hx ⟨y, hy, hR⟩
    rcases le_or_gt 0 y with hy0 | hy0
    · rw [abs_of_nonneg hy0] at hy
      obtain ⟨y', hy'0, hy', hR'⟩ := hq2.1 (x - y) (sub_pos.mpr hy)
      refine ⟨y + y', ?_, hcomp _ _ _ _ _ hy0 hy'0 hR hR'⟩
      rw [abs_of_nonneg (add_nonneg hy0 hy'0)]
      exact lt_sub_iff_add_lt'.mp hy'
    · have hR1 : R w (-y) v := hrefl _ _ _ hR
      have hxy : 0 < x + y := by have := (abs_lt.mp hy).1; rw [neg_lt] at this; exact neg_lt_iff_pos_add.mp this
      obtain ⟨y', hy'0, hy', hR'⟩ := hq2.2 (x + y) hxy
      have hc := hcomp _ _ _ _ _ hy'0 (neg_nonneg.mpr hy0.le) hR' hR1
      refine ⟨-(y' + -y), ?_, hrefl _ _ _ hc⟩
      rw [abs_neg, abs_of_nonneg (add_nonneg hy'0 (neg_nonneg.mpr hy0.le)), ← sub_eq_add_neg]
      exact sub_lt_iff_lt_add.mpr hy'
  -- Step 3: every `𝒯_F`-open set containing `w` contains `u`.
  have hgen : ∀ O, GenerateOpen {s | ∃ v x, 0 < x ∧ s = cone R v x} O → w ∈ O → u ∈ O := by
    intro O hO
    induction hO with
    | basic s hs => obtain ⟨v, x, hx, rfl⟩ := hs; exact key v x hx
    | univ => intro; trivial
    | inter s t _ _ ihs iht => intro h; exact ⟨ihs h.1, iht h.2⟩
    | sUnion S _ ih => rintro ⟨s, hs, hws⟩; exact ⟨s, hs, ih s hs hws⟩
  -- Step 4: T1 for `𝒯_F` makes `{u}ᶜ` open, and it contains `w` unless `u = w`.
  by_contra hne
  letI := coneTopology R
  haveI := hT1
  have hopen : IsOpen ({u}ᶜ : Set W) := isOpen_compl_singleton
  exact hgen _ hopen (fun h => hne (Set.mem_singleton_iff.mp h).symm) rfl

/-! ## Axiom audit: every headline theorem uses only `propext`, `Classical.choice`, `Quot.sound` -/

#print axioms t1Space_nbhdTopology_iff_limit
#print axioms coneTopology_le_nbhdTopology
#print axioms t1Space_coneTopology_of_limit
#print axioms r0Space_nbhdTopology_of_limit
#print axioms r0Space_coneTopology_of_limit
#print axioms limit_eq_iff
#print axioms nbhdTopology_isClosed_iff
#print axioms discreteTopology_nbhdTopology_iff
#print axioms nbhdTopology_eq_mkOfNhds
#print axioms continuous_nbhdTopology_of_history
#print axioms finalTopology_le_nbhdTopology
#print axioms isOpen_cone_of_triangle
#print axioms coneTopology_eq_nbhdTopology_iff
#print axioms limit_of_t1Space_coneTopology

end FormalSystem.Semantics.TaskFrame
