// ============================================================================
// p2-frame-classes.typ
// Part I chapter -- Frame Classes and Extensions
// Lean name ground truth: ProofSystem/Axioms.lean, FrameConditions/,
// Syntax/Atom.lean (see ../SYNC-MAP.md).
// ============================================================================

#import "../template.typ": *
#import "../generated/status.typ": base-count, dense-only-count, discrete-only-count

= Frame Classes and Extensions

#chapter-header(
  description: [How the base proof system of @sec:formulas and the proof theory chapter extends to dense and discrete linear orders, how the Until/Since-primitive language relates to derived Next/Previous operators, and the status of conservativity between *TM*'s tense-primitive and Until/Since-primitive language levels.],
  dependencies: [Chapters 1--3 (syntax, semantics, proof theory).],
)


== The `FrameClass` Partial Order

The `FrameClass` classification that parameterizes `DerivationTree` (@sec:formulas) is a three-element inductive type with an explicit partial order, defined in `ProofSystem/Axioms.lean`:

#leansrc("FormalSystem.ProofSystem", "FrameClass")
```
inductive FrameClass where
  | Base
  | Dense
  | Discrete
```

`Base` is the bottom element (`FrameClass.base_le`); `Dense` and `Discrete` are incomparable extensions of `Base` -- density and discreteness are jointly inconsistent frame properties, so no derivation may combine both.
Every axiom constructor carries a minimum frame class via `Axiom.minFrameClass` (`ProofSystem/Axioms.lean:456-462`), and `DerivationTree`'s axiom rule enforces `ax.minFrameClass ≤ fc`:

#figure(
  table(
    columns: 2,
    stroke: none,
    align: (left, left),
    table.hline(),
    table.header([*Frame class*], [*Axioms assigned*]),
    table.hline(),
    [`Base`], [#base-count axioms (layers 1--5): all base propositional, modal, BX temporal, interaction, and uniformity axioms],
    [`Dense`], [#dense-only-count axioms: `density`, `dense_indicator`],
    [`Discrete`], [#discrete-only-count axioms: `prior_UZ`, `prior_SZ`, `z1`],
    table.hline(),
  ),
  caption: [`Axiom.minFrameClass` breakdown (`ProofSystem/Axioms.lean:407-422` doc comment; counts regenerated by `scripts/typst-status-counts.sh`).],
)

== Semantic Frame-Condition Typeclasses

The syntactic `FrameClass` inductive and its order live entirely inside `ProofSystem/Axioms.lean`, above.
The frame-condition *semantics* for dense and discrete orders lives elsewhere: `FrameConditions/FrameClass.lean` defines a separate typeclass hierarchy over a generic duration type `D`, used by the validity/soundness bridge below:

- `LinearTemporalFrame D` -- the base bundle typeclass (`[AddCommGroup D] [LinearOrder D] [IsOrderedAddMonoid D]`).
- `SerialFrame D` -- adds `Nontrivial`, `NoMaxOrder`, `NoMinOrder` (guarantees BX1/BX1$'$ seriality).
- `DenseTemporalFrame D` -- adds `DenselyOrdered D`.
- `DiscreteTemporalFrame D` -- adds `SuccOrder D`, `PredOrder D`, `IsSuccArchimedean D`.

`FrameConditions/Validity.lean` defines frame-relative validity over this hierarchy (`ValidOver`, `ValidLinear`, `ValidDenseFc`, `ValidDiscreteFc`, and the concrete abbreviation `ValidOverInt`).
`FrameConditions/Soundness.lean` and `Compatibility.lean` bridge this semantic layer to the syntactic `FrameClass`/`Axiom.minFrameClass` classification above (`soundness_linear`, `soundness_dense`, `soundness_discrete`, and the `AxiomLinearCompatible`/`AxiomDenseCompatible`/`AxiomDiscreteCompatible` typeclasses with per-axiom instances) -- this is the machinery underlying the frame-class soundness theorems already stated in @sec:notes.
All four `FrameConditions/` files are sorry-free.#footnote[The prose doc comments inside `Soundness.lean` and `Compatibility.lean` cite axiom counts from an earlier stage of the axiom system; the counts used in this book are regenerated directly from source by `scripts/typst-status-counts.sh`.]

== Duration Groups and the Three Classes

The frame classes are best understood through the duration groups that realize them.
Every duration type must be a nontrivial linearly ordered abelian group with no greatest or least element (the `SerialFrame` bundle), which is what validates the seriality axioms BX1/BX1$'$: every time has a strictly later and a strictly earlier time.
Within that envelope, the two extensions pick out incompatible order structures:

#figure(
  table(
    columns: 3,
    stroke: none,
    align: (left, left, left),
    table.hline(),
    table.header([*Duration group*], [*Class*], [*Why*]),
    table.hline(),
    [$ZZ$], [`Discrete`], [Every element has an immediate successor and predecessor, and iterated succession reaches every later element],
    [$QQ$, $RR$], [`Dense`], [Strictly between any two elements lies a third],
    [$ZZ times ZZ$ (lexicographic)], [`Base` only], [Not dense (nothing lies between $(0,0)$ and $(0,1)$), yet succession from $(0,0)$ never reaches $(1,0)$],
    table.hline(),
  ),
  caption: [Representative duration groups for each frame class.],
)

The lexicographic product is the instructive case: it shows that `Base` is not merely the union of the two extensions.
A base-class derivation is sound over *every* admissible duration group, including orders that are neither dense nor discrete, which is why the base axioms must avoid both the density schema and the Prior/Z1 layer.

*Density and discreteness exclude each other.*
The object-language witness is the discreteness indicator $U(top, bot)$ ("there is an immediate successor": the guard interval to the witness is empty).
On a discrete order every point has an immediate successor, so $U(top, bot)$ holds everywhere; on a dense order the open interval between any point and any strictly later point is nonempty, so the guard $bot$ can never hold throughout it and $U(top, bot)$ fails everywhere.
A derivation combining the DI axiom $not U(top, bot)$ with the Prior/Z1 layer would therefore be sound over no frame at all, and the partial order on `FrameClass` -- with `Dense` and `Discrete` incomparable -- makes such a combination unformulable rather than merely unsound.

*Worked validity: the density schema.*
DN ($G G phi.alt arrow.r G phi.alt$) is valid over dense orders by a two-step argument.
Suppose $G G phi.alt$ holds at time $x$ and let $y > x$ be arbitrary; density supplies $z$ with $x < z < y$; from $G G phi.alt$ at $x$ we get $G phi.alt$ at $z$, and since $y > z$ this gives $phi.alt$ at $y$.
Over $ZZ$ the argument breaks exactly at the appeal to density -- there is no $z$ strictly between $x$ and its immediate successor -- and indeed DN fails there: take $phi.alt$ true everywhere except at $x + 1$.
Then $G phi.alt$ fails at $x$; but for every $y > x$, any $w > y$ satisfies $w gt.eq x + 2$, so $G phi.alt$ holds at every $y > x$ and $G G phi.alt$ holds at $x$.

*Worked validity: the discrete layer.*
Prior-UZ ($F phi.alt arrow.r U(phi.alt, not phi.alt)$) says that if $phi.alt$ holds somewhere in the future, it holds at a *nearest* future point -- between now and that first witness, $phi.alt$ everywhere fails.
Over $ZZ$ this is the least-number principle applied to the set of future $phi.alt$-times; over $QQ$ it fails, since ${ y : y > x, phi.alt "at" y }$ may have no least element (take $phi.alt$ to hold exactly on the open interval $(x, x+1)$).
Z1 ($G(G phi.alt arrow.r phi.alt) arrow.r (F G phi.alt arrow.r G phi.alt)$) is the backward-induction principle of successor-Archimedean orders @doets1987: if $phi.alt$ is inductive along the strict future order and holds from some future point onward, discreteness lets the property propagate backward step by step to every future time.
Both principles are axioms of frame class `Discrete` and are unavailable at `Base`, matching their failure over dense groups.

*Monotonicity.*
Because `Base` sits below both extensions, every base-class theorem is automatically a theorem of both extended systems: `DerivationTree.lift` coerces derivations upward along the `FrameClass` order, and the soundness theorems for the three classes (`soundness_linear`, `soundness_dense`, `soundness_discrete`) confirm semantically that nothing is lost in the coercion.

== Paper Correspondence: DF, DN, and CO #footnote[The paper's Discreteness (DF), Density (DN), and Completeness (CO) frame properties, `possible_worlds.tex` §3.3 (:1162-1256) and appendices `app:discrete`/`app:dense`/`app:complete`.]

The paper's Discreteness and Density frame properties correspond to the `DiscreteTemporalFrame`/`DenseTemporalFrame` typeclasses above, and are formalized via the `Discrete`/`Dense` `FrameClass` axiom layers.
The paper's Completeness property (giving the $op("TM")_c$ and $op("TM")_(d c)$ extensions over Dedekind-complete flows of time) is a paper-side result (`possible_worlds.tex` `app:complete`): the formalization has no `Complete`-style typeclass and no matching `FrameClass` layer.
This asymmetry (Discreteness/Density formalized, Completeness not) matches the three-element `FrameClass` type having no fourth constructor.

== Next and Previous as Derived Operators

The paper's *Next* and *Previous* operators are derived, not primitive, in the Lean formalization.
`Syntax/Formula.lean` defines them with the formula argument *first* and $bot$ as the guard (the "Burgess convention" @burgess1982axioms: event first, guard second):

#leansrc("FormalSystem.Syntax.Formula", "next")
```
def next (φ : Formula) : Formula := Formula.untl φ Formula.bot   -- X(φ) := φ U ⊥
def prev (φ : Formula) : Formula := Formula.snce φ Formula.bot   -- Y(φ) := φ S ⊥
```

not `⊥ U φ` as an event-second convention would give.
$X(phi.alt)$ at $t$ means $phi.alt$ holds at the immediate successor of $t$ (event $= phi.alt$ at the immediate successor, guard $= bot$ vacuously true at no strictly-intermediate time); dually for `prev`.
The unfold lemmas confirming this characterization are `next_unfold` (`Automation/Normalization.lean:70`) and `prev_unfold` (`Automation/Normalization.lean:73`), both `@[simp]`-tagged and proven by `rfl`.
The paper's own Next/Previous theorem is a paper-side result with no Lean counterpart.

== Conservativity Between *TM* and *TM*#super[+] <sec:conservative-extension>

An earlier presentation of this book cited a fresh-atom lifting technique here (extending the atom set with one marker atom and projecting derivations back down), used as infrastructure for @sec:design-choices's fresh-atom argument that irreflexivity is not modally definable.
That module has since been archived and is no longer part of the live formalization; the live resource the irreflexivity argument actually needs is simpler and still present, the primitive fact that a fresh atom exists outside any finite set (`Atom.exists_fresh`, `Syntax/Atom.lean`).
Note in passing that this atom-extension technique was never a formalization of the paper's *TM*-versus-*TM*#super[+] conservativity claim below, despite the coincidence of name --- it extended the *atom set*, not the *operator set*.

The paper's own conservativity claim is the one this section should state, and it is *not* the unconditional theorem an earlier draft of this book implied.
`thm:ConservativeExtension` no longer exists in the paper: `def:TMplus`'s footnote replaces it and makes *no* conservativity claim, stating instead a four-part status.

#theorem("Conservativity Status (TM vs. TM+)")[
  + *Backward* (every $op("BL")$-theorem of *TM*, $op("TM")_f$, $op("TM")_d$, $op("TM")_c$ survives in *TM*#super[+], $op("TM")^+_f$, $op("TM")^+_d$, $op("TM")^+_c$ respectively): holds *unconditionally*, since $op("BL")$ embeds into $op("BL")^+$.
  + *Forward* (does the richer language prove genuinely new $op("BL")$-theorems) *fails* for the base case, witnessed by the (DD) split validity of @sec:metalogic.
  + *Forward fails unconditionally* for the discrete extension, witnessed by axiom TMP-Z1: a theorem of the discrete extension's base tense logic and so a $op("TM")^+_f$-theorem trivially, yet unsound over the non-Archimedean discrete order $ZZ times_(op("lex")) ZZ$ and so not a $op("TM")_f$-theorem.
  + *Forward remains open* for the dense and complete extensions, with no known counterexample.
]#footnote[`def:TMplus`'s footnote, replacing the deleted `thm:ConservativeExtension`. @brastmckie2026possibleworlds]

No conservativity claim is therefore made for *TM*#super[+] over *TM*.
A separate, Lean-side task targets a formalized conservativity bridge; its premise is the now-deleted `thm:ConservativeExtension`, so that task's scope is affected by this correction (recorded in this task's findings note).
