/-
Probe 718 (R1 probe 2): **the finite-graph `⊡` summary, by reachability alone** — decide `⊡ψ` for
`ψ` a single temporal operator over state formulas on a frame generated by a finite step graph,
using reachability only and no determinization. The route-killer test for R1.

**Outcome: POSITIVE for the forward factor, on the fixture below.** `will_iff_allPathsMeet`
establishes `⊡(F p)` at a seam state `w₀` iff every forward root path from `w₀` meets the
`p`-set, routed through the general `⊡` clause (`PlusTruth.stab_iff`) and the landed fact that
possible worlds over ℤ are exactly bi-infinite step paths (`IntNormalForm.lean`'s
`WorldHistory.isStepPath`, `FrameOver.worldHistoryOfStepPath`, `FrameOver.ofSlicedStep_step`) —
**not** through the promoted keystone's ray/ω-sequence `Equiv`s, which live in a sibling probe
file outside the Lake build graph and so cannot be `import`ed from here (every probe in this
collection imports only `FormalSystem`, never another probe — see
`scripts/check-evidence-probes.sh`'s header). This is a deliberate, equivalent substitute route
and not a re-derivation of the keystone: the keystone is a REPRESENTATION fact (the stab fibre
IS a ray/ω-sequence product); this file never needs that representation, only the bare `⊡`
clause's universal quantifier over histories, which is a `FormalSystem` primitive already.
`decide_will` supplies the promised computational content: on the fixture, `⊡(F p)` is
decidably **False** at every seam state, witnessed by the constant-avoid-`p` continuation.

**The backward dual is NOT separately proved.** The fixture's relation is symmetric under time
reversal (`Rf` ignores both its time and direction arguments), so the backward statement for
`⊡(P p)` is the forward statement verbatim with "forward path" read as "backward path"; proving
it would exercise no machinery this file does not already exercise forward, and the research
round's scope hypothesis bounds this phase at the single-direction shapes. This is recorded here
rather than silently omitted.

What this does NOT do: it bounds no width, no tail-period, commits to no complexity claim, and
decides nothing beyond this one fixture and this one formula shape (`⊡(Fp)`, a single temporal
operator, no nesting). It does not touch the keystone, which stands exactly as promoted.

Compile-check from the repository root with:
  lake env lean specs/evidence/seam-gluing-ray-product/finite-graph-stab-summary.lean
-/
import FormalSystem

open FormalSystem.Syntax FormalSystem.Semantics FormalSystem.PlusLanguage
open FormalSystem.PlusLanguage.PlusFormula

namespace Probe718FiniteGraph

/-! ## The fixture: a total (hence genuinely branching) step graph on `Bool` -/

/-- The fixture's one-step relation: the **complete** graph on `Bool`, time-independent. Total,
hence bi-serial trivially, and branching at every state — the real test for Phase 5's
existential/universal divergence, which reuses this same fixture. -/
def Rf : ℤ → Bool → Bool → Prop := fun _ _ _ => True

theorem Rf_fwd : ∀ (t : ℤ) (w : Bool), ∃ u, Rf t w u := fun _ _ => ⟨true, trivial⟩
theorem Rf_bwd : ∀ (t : ℤ) (w : Bool), ∃ v, Rf (t - 1) v w := fun _ _ => ⟨true, trivial⟩

/-- The fixture frame: `Bool`, `Fintype`, `Nonempty`, bi-serial — exactly the shape the plan
calls for, reused verbatim by Phase 5. -/
def Ff : FrameOver intOrder := FrameOver.ofSlicedStep Rf Rf_fwd Rf_bwd

instance : Ff.IsRegular := FrameOver.ofSlicedStep_isRegular Rf Rf_fwd Rf_bwd

/-- The distinguished atom, read off the `Bool` component: `p` holds exactly at `true`. -/
def pa : Atom := ⟨"p", none⟩

/-- The fixture model: `p`'s valuation is the state's `Bool` component. -/
def Mf : TaskModel Ff.toTaskFrame where
  valuation q _ := q.2 = true

/-! ## Forward reachability on the fixture graph -/

/-- A **forward root path** from `w₀`: any `Bool`-sequence starting at `w₀`. The `Rf`-step
hypothesis is carried for faithfulness to the general shape ("every forward root path") even
though `Rf` being total makes it vacuous on this fixture. -/
def IsFwdPath (w₀ : Bool) (g : ℕ → Bool) : Prop := g 0 = w₀ ∧ ∀ n, Rf 0 (g n) (g (n + 1))

/-- The **AF-shaped reachability condition**: every forward root path from `w₀` meets the
`p`-set at some strictly later position. -/
def AllPathsMeet (w₀ : Bool) : Prop := ∀ g : ℕ → Bool, IsFwdPath w₀ g → ∃ n, 0 < n ∧ g n = true

/-!
## The summary theorem

`⊡(Fp)` at a seam state is exactly `AllPathsMeet` at that state's `Bool` component.
-/

theorem will_iff_allPathsMeet (τ : WorldHistory Ff.toTaskFrame) (t : ℤ) :
    PlusTruthAt Mf τ t (.stab (someFuture (.atom pa))) ↔ AllPathsMeet (τ.state t).2 := by
  rw [PlusTruth.stab_iff]
  generalize hcw : τ.state t = cw
  obtain ⟨c, w₀⟩ := cw
  simp only at hcw ⊢
  constructor
  · intro h g hg
    obtain ⟨hg0, -⟩ := hg
    let h' : ℤ → Bool := fun z => if t ≤ z then g (z - t).toNat else w₀
    let f : ℤ → Ff.WorldState := fun z => (z + (c - t), h' z)
    have hstep : IsStepPath Ff f := by
      intro z
      refine (FrameOver.ofSlicedStep_step Rf Rf_fwd Rf_bwd (f z) (f (z + 1))).mpr ⟨?_, trivial⟩
      show z + 1 + (c - t) = z + (c - t) + 1
      ring
    have hft : f t = (c, w₀) := by
      have h1 : t + (c - t) = c := by ring
      have h2 : h' t = w₀ := by
        show (if t ≤ t then g (t - t).toNat else w₀) = w₀
        rw [if_pos le_rfl]
        simpa using hg0
      show (t + (c - t), h' t) = (c, w₀)
      rw [h1, h2]
    set σ := FrameOver.worldHistoryOfStepPath Ff f hstep with hσdef
    have hσt : σ.state t = (c, w₀) := hft
    have hagree : (c, w₀) = σ.state t := hσt.symm
    obtain ⟨s, hts, hs, -⟩ := h σ hagree
    have hts' : (t : ℤ) < (s : ℤ) := hts
    refine ⟨(s - t).toNat, by omega, ?_⟩
    have hval : (σ.state s).2 = true := hs
    have hσs : σ.state s = f s := rfl
    have hfs2 : (f s).2 = true := hσs ▸ hval
    have hs_eq : h' s = g (s - t).toNat := by
      show (if t ≤ s then g (s - t).toNat else w₀) = g (s - t).toNat
      rw [if_pos (le_of_lt hts)]
    show g (s - t).toNat = true
    rw [← hs_eq]
    exact hfs2
  · intro h σ hagree
    have hw₀ : σ.state t = (c, w₀) := hagree.symm
    have hstep : IsStepPath Ff σ.path := σ.isStepPath
    obtain ⟨n, hn, hgn⟩ := h (fun n => (σ.path (t + n)).2) ⟨by
        show (σ.path (t + (0 : ℕ))).2 = w₀
        have h0 : (t + ((0:ℕ):ℤ)) = t := by norm_num
        rw [h0]
        show (σ.state t).2 = w₀
        rw [hw₀], fun n => trivial⟩
    have hn' : (0 : ℤ) < (n : ℤ) := by exact_mod_cast hn
    refine ⟨t + n, by linarith, ?_, fun r _ _ => PlusTruth.top_true (M := Mf) (τ := σ) (t := r)⟩
    show (σ.state (t + n)).2 = true
    exact hgn

/-! ## Computational content: `⊡(Fp)` is decidably False at every seam on the fixture -/

/-- The constant-avoid-`p` continuation: starts at `w₀`, then stays at `false` forever,
witnessing that `AllPathsMeet` fails at every state. -/
theorem not_allPathsMeet (w₀ : Bool) : ¬ AllPathsMeet w₀ := by
  intro h
  obtain ⟨n, hn0, hn⟩ := h (fun n => if n = 0 then w₀ else false) ⟨if_pos rfl, fun _ => trivial⟩
  rw [if_neg (by omega)] at hn
  simp at hn

/-- **`⊡(Fp)` is decidably False at every seam state of the fixture.** The decision function is
the constant `false`; its correctness is `not_allPathsMeet` composed with
`will_iff_allPathsMeet`. -/
theorem decide_will (τ : WorldHistory Ff.toTaskFrame) (t : ℤ) :
    ¬ PlusTruthAt Mf τ t (.stab (someFuture (.atom pa))) := by
  rw [will_iff_allPathsMeet]
  exact not_allPathsMeet _

instance decidable_will (τ : WorldHistory Ff.toTaskFrame) (t : ℤ) :
    Decidable (PlusTruthAt Mf τ t (.stab (someFuture (.atom pa)))) :=
  Decidable.isFalse (decide_will τ t)

end Probe718FiniteGraph

/-! ## Axiom record -/

#print axioms Probe718FiniteGraph.will_iff_allPathsMeet
#print axioms Probe718FiniteGraph.not_allPathsMeet
#print axioms Probe718FiniteGraph.decide_will
