#!/usr/bin/env python3
"""Measure the structural partitions the publication refactor programme depends on.

Every number in ``docs/development/PUBLICATION_REFACTOR.md`` and in ADR-011 is
regenerated by this script, never typed.  It reads the live tree through
``scripts/lib/import_graph.py`` (leading-import parse, archive excluded by
directory name) and prints markdown tables, or JSON with ``--json``.

Usage (run from the repository root):

  measure-refactor-partitions.py upward-edges
  measure-refactor-partitions.py weakcanonical-partition
  measure-refactor-partitions.py automation-partition
  measure-refactor-partitions.py namespace-audit
  measure-refactor-partitions.py all
  measure-refactor-partitions.py --check      # exit 1 if the Expressiveness set leaks

The four measurements:

  upward-edges             Every import that runs *up* the layer stack recorded
                           in ORGANISATION.md (Syntax/ProofSystem/ForMathlib=0,
                           Semantics=1, Metalogic=2, Theorems=3, Automation=4,
                           Examples=5), grouped by source and target directory,
                           with the Theorems <-> Metalogic pair called out.
  weakcanonical-partition  Each module under Metalogic/WeakCanonical/ classified
                           by whether BXCanonical is in its transitive closure;
                           the proposed Expressiveness set (EXPRESSIVENESS_SET
                           below) with its file and line counts, the residual
                           set, and every edge from the Expressiveness set into
                           the residual or into BXCanonical (expected: none).
  automation-partition     The Automation modules the *library* needs -- the
                           union of the closures of every non-Automation
                           library module, with Examples/, MainResults and the
                           tooling-only TraceExport pruned from the walk --
                           against the complement, which is dataset/ML tooling.
  namespace-audit          Each live file's first `namespace` against its
                           module path: equal-or-descendant, ancestor, unrelated
                           or none.

``--check`` is the pre-move gate for the Expressiveness extraction: it exits 0
only when the Expressiveness set has no edge into the residual WeakCanonical
set and none into BXCanonical.  Never weaken it; if it fails, the offending
edges are the work, and the relocation has to be dependency-first.

Measured on commit 220e94ea4 (the tree the programme was written against):
  upward-edges              16 import lines from the five lower layers into
                            Automation, 11 of them into the attribute-only
                            files TruthNormAttr and LemmaDB (the programme's
                            source analysis had said 17 and 12; the script is
                            right); 4 Theorems files import
                            Metalogic.Core.DeductionTheorem; 29 Metalogic files
                            import Theorems across 47 lines
  weakcanonical-partition   Expressiveness 141 files / 104,087 lines,
                            residual 38 files / 28,472 lines, 0 leaking edges;
                            BXCanonical-free by closure: 150 of 179
  automation-partition      9 library-needed modules (3,419 lines), 4
                            user-facing tactic modules (1,238), 25 tooling
                            modules including TraceExport (14,747)
  namespace-audit           279 equal-or-descendant / 187 ancestor / 24
                            unrelated / 43 with no namespace; 15 of the 24 are
                            the {Plus,Minus,Star}Language files (not 17)
Where a document and this output disagree, this output is right; the document
records the discrepancy rather than the other way round.
"""

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "lib"))
from import_graph import ImportGraph, first_namespace  # noqa: E402

LIB = "FormalSystem"

# ORGANISATION.md's layer table.  A top-level module such as `FormalSystem.Init`
# or `FormalSystem.MainResults` has no layer and never contributes an edge.
LAYERS = {
    "Syntax": 0, "ProofSystem": 0, "ForMathlib": 0, "Init": 0,
    "Semantics": 1,
    "Metalogic": 2,
    "Theorems": 3,
    "Automation": 4,
    "Examples": 5,
}

WEAK = f"{LIB}.Metalogic.WeakCanonical"
BX = f"{LIB}.Metalogic.BXCanonical"

# The proposed Metalogic/Expressiveness/ set, named relative to WeakCanonical/.
# A name is a subtree (every module below it) or a single module.
EXPRESSIVENESS_SET = (
    "Kamp", "EFGames", "Expressiveness", "Separation",
    "NormalForm", "MonadicFO", "StaviConnectives",
    "PriorDefs", "PriorDefsDense", "PriorExpressiveness", "PriorExpressivenessDense",
    "Table", "EFGameTactics",
)

# User-facing tactic modules: library API that no library file imports (a user
# does), so the closure walk cannot see them.  Classified as library, not tooling.
USER_FACING_TACTICS = frozenset(
    f"{LIB}.Automation.Tactics.{n}" for n in ("Commands", "Deduction", "Search", "UserTactics")
)

# Pruned from the automation-partition walk: these import Automation on purpose
# (Examples imports the whole aggregator; MainResults audits everything;
# TraceExport is tooling whose only consumer is an exe root).
AUTOMATION_PRUNE_PREFIXES = (f"{LIB}.Examples",)
AUTOMATION_PRUNE_MODULES = (
    f"{LIB}.Examples",
    f"{LIB}.MainResults",
    f"{LIB}.Metalogic.Decidability.TraceExport",
    f"{LIB}.Automation",          # the aggregator imports every Automation module
    f"{LIB}.FormalSystem",        # the two roots import the aggregator
    LIB,
)


def top_dir(module):
    parts = module.split(".")
    return parts[1] if len(parts) > 1 and parts[0] == LIB else None


def layer_of(module):
    d = top_dir(module)
    return LAYERS.get(d) if d else None


def md_table(headers, rows):
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# upward-edges
# ---------------------------------------------------------------------------

def measure_upward_edges(g):
    lib_modules = [m for m in g.modules if m.startswith(LIB + ".")]
    edges = []  # (src_module, tgt_module)
    for src in lib_modules:
        ls = layer_of(src)
        if ls is None:
            continue
        for tgt in g.edges[src]:
            lt = layer_of(tgt)
            if lt is None or lt <= ls:
                continue
            edges.append((src, tgt))
    classes = {}
    for src, tgt in edges:
        classes.setdefault((top_dir(src), top_dir(tgt)), []).append((src, tgt))
    into_automation = [(s, t) for s, t in edges if top_dir(t) == "Automation"
                       and top_dir(s) in ("Syntax", "Semantics", "ProofSystem", "Theorems", "Metalogic")]
    # Both directions of the Theorems <-> Metalogic pair are computed directly
    # rather than read off `edges`: the table puts Metalogic (2) below Theorems
    # (3), so only Metalogic -> Theorems counts as "upward" above, while the
    # reverse direction is what the table calls downward and is invisible there.
    theorems_to_metalogic = sorted({s for s in lib_modules if top_dir(s) == "Theorems"
                                    for t in g.edges[s] if top_dir(t) == "Metalogic"})
    metalogic_to_theorems = sorted({s for s in lib_modules if top_dir(s) == "Metalogic"
                                    for t in g.edges[s] if top_dir(t) == "Theorems"})
    return {
        "edge_count": len(edges),
        "into_automation_line_count": len(into_automation),
        "classes": {f"{a} -> {b}": sorted(v) for (a, b), v in sorted(classes.items())},
        "theorems_files_importing_metalogic": theorems_to_metalogic,
        "metalogic_files_importing_theorems": metalogic_to_theorems,
    }


def print_upward_edges(r):
    print("## Upward edges (source layer below target layer per ORGANISATION.md)\n")
    print(f"Total upward import lines: {r['edge_count']} "
          f"({r['into_automation_line_count']} from the five lower layers into Automation)\n")
    for cls, pairs in r["classes"].items():
        print(f"### {cls} ({len(pairs)} lines)\n")
        print(md_table(["Source module", "Imports"], pairs))
        print()
    print(f"### Theorems <-> Metalogic\n")
    print(f"- Theorems files importing Metalogic: {len(r['theorems_files_importing_metalogic'])}")
    for m in r["theorems_files_importing_metalogic"]:
        print(f"  - `{m}`")
    print(f"- Metalogic files importing Theorems: {len(r['metalogic_files_importing_theorems'])}")
    print()


# ---------------------------------------------------------------------------
# weakcanonical-partition
# ---------------------------------------------------------------------------

def in_expressiveness_set(module):
    rel = module[len(WEAK) + 1:]
    head = rel.split(".")[0]
    return head in EXPRESSIVENESS_SET


def measure_weakcanonical(g):
    members = g.under(WEAK)
    aggregator = WEAK if WEAK in members else None
    modules = [m for m in members if m != WEAK]
    expr = sorted(m for m in modules if in_expressiveness_set(m))
    resid = sorted(m for m in modules if not in_expressiveness_set(m))
    expr_set, resid_set = set(expr), set(resid)

    def bx_free(m):
        return not any(c == BX or c.startswith(BX + ".") for c in g.closure(m))

    pure = sorted(m for m in modules if bx_free(m))
    impure = sorted(m for m in modules if m not in set(pure))

    leaks = []
    for m in expr:
        for t in g.edges[m]:
            if t in resid_set or t == BX or t.startswith(BX + "."):
                leaks.append((m, t))
    importers_outside = {}
    for m in expr:
        for src in g.reverse.get(m, ()):
            if src not in expr_set:
                importers_outside.setdefault(src, []).append(m)

    def lines(ms):
        return sum(g.line_count(m) for m in ms)

    subtree_rows = []
    for name in EXPRESSIVENESS_SET:
        ms = [m for m in expr if m[len(WEAK) + 1:].split(".")[0] == name]
        subtree_rows.append((name, len(ms), lines(ms)))

    return {
        "aggregator": aggregator,
        "module_count": len(modules),
        "expressiveness": {"files": len(expr), "lines": lines(expr), "modules": expr,
                           "subtrees": subtree_rows},
        "residual": {"files": len(resid), "lines": lines(resid), "modules": resid},
        "bxcanonical_free_by_closure": {"pure": len(pure), "impure": len(impure),
                                        "impure_modules": impure},
        "expressiveness_not_bx_free": sorted(m for m in expr if m not in set(pure)),
        "leaking_edges": leaks,
        "importers_outside_set": {k: sorted(v) for k, v in sorted(importers_outside.items())},
    }


def print_weakcanonical(r):
    e, s = r["expressiveness"], r["residual"]
    print("## WeakCanonical partition\n")
    print(f"Modules under `Metalogic/WeakCanonical/`: {r['module_count']}"
          + (f" (plus the sibling aggregator `{r['aggregator']}`, not counted)" if r["aggregator"] else "") + "\n")
    print(md_table(["Set", "Files", "Lines"],
                   [("Expressiveness (proposed move)", e["files"], f"{e['lines']:,}"),
                    ("Residual WeakCanonical", s["files"], f"{s['lines']:,}")]))
    print()
    print("### Expressiveness set by subtree\n")
    print(md_table(["Name (relative to WeakCanonical/)", "Files", "Lines"],
                   [(n, f, f"{l:,}") for n, f, l in e["subtrees"]]))
    print()
    p = r["bxcanonical_free_by_closure"]
    print(f"BXCanonical-free by transitive closure: {p['pure']} of {r['module_count']} "
          f"({p['impure']} reach BXCanonical)\n")
    if r["expressiveness_not_bx_free"]:
        print("Expressiveness modules that reach BXCanonical (MUST be empty):")
        for m in r["expressiveness_not_bx_free"]:
            print(f"- `{m}`")
        print()
    print(f"### Edges from the Expressiveness set into the residual set or BXCanonical: "
          f"{len(r['leaking_edges'])}\n")
    for src, tgt in r["leaking_edges"]:
        print(f"- `{src}` -> `{tgt}`")
    if r["leaking_edges"]:
        print()
    print("### Importers of the Expressiveness set from outside it\n")
    for src, tgts in r["importers_outside_set"].items():
        print(f"- `{src}` ({len(tgts)} line{'s' if len(tgts) != 1 else ''})")
    print()
    print("### Residual modules\n")
    for m in s["modules"]:
        print(f"- `{m}`")
    print()


# ---------------------------------------------------------------------------
# automation-partition
# ---------------------------------------------------------------------------

def measure_automation(g):
    auto_prefix = f"{LIB}.Automation."
    automation = sorted(m for m in g.modules if m.startswith(auto_prefix))
    prune = set(AUTOMATION_PRUNE_MODULES) | {
        m for m in g.modules if any(m == p or m.startswith(p + ".") for p in AUTOMATION_PRUNE_PREFIXES)
    }
    roots = [m for m in g.modules
             if m.startswith(LIB + ".") and not m.startswith(auto_prefix) and m not in prune]
    needed = set()
    needed_by = {}
    for r in roots:
        for c in g.closure(r, exclude=frozenset(prune)):
            if c.startswith(auto_prefix):
                needed.add(c)
                # record direct importers only, for the table
        for t in g.edges[r]:
            if t.startswith(auto_prefix):
                needed_by.setdefault(t, set()).add(r)
    needed = sorted(needed)
    user_facing = sorted(m for m in automation if m in USER_FACING_TACTICS)
    tooling = sorted(m for m in automation if m not in set(needed) and m not in USER_FACING_TACTICS)
    tooling.append(f"{LIB}.Metalogic.Decidability.TraceExport")
    tooling.sort()
    exe_roots = sorted(m for m in tooling if m.endswith("Main"))
    tests_importing_tooling = {}
    for m in g.modules:
        if not m.startswith("BimodalTest"):
            continue
        hits = [t for t in g.edges[m] if t in set(tooling)]
        if hits:
            tests_importing_tooling[m] = hits

    def lines(ms):
        return sum(g.line_count(m) for m in ms)

    return {
        "library_needed": {"count": len(needed), "lines": lines(needed), "modules": needed,
                           "direct_importers": {k: sorted(v) for k, v in sorted(needed_by.items())}},
        "user_facing_tactics": {"count": len(user_facing), "lines": lines(user_facing),
                                "modules": user_facing},
        "tooling": {"count": len(tooling), "lines": lines(tooling), "modules": tooling,
                    "exe_roots": exe_roots},
        "tests_importing_tooling": tests_importing_tooling,
        "pruned_roots": sorted(prune & set(g.modules)),
    }


def print_automation(r):
    n, u, t = r["library_needed"], r["user_facing_tactics"], r["tooling"]
    print("## Automation partition\n")
    print(md_table(["Set", "Modules", "Lines"],
                   [("Library-needed Automation modules (by closure)", n["count"], f"{n['lines']:,}"),
                    ("User-facing tactic modules (library API, imported by no library file)",
                     u["count"], f"{u['lines']:,}"),
                    ("Tooling (dataset / ML / benchmark / exe roots, plus TraceExport)",
                     t["count"], f"{t['lines']:,}")]))
    print()
    print("### Library-needed modules and their direct importers outside Automation\n")
    rows = []
    for m in n["modules"]:
        imps = n["direct_importers"].get(m, [])
        rows.append((f"`{m}`", len(imps), ", ".join(f"`{i}`" for i in imps[:4]) + (" ..." if len(imps) > 4 else "")))
    print(md_table(["Module", "Direct importers", "Examples"], rows))
    print()
    print("### Tooling modules\n")
    for m in t["modules"]:
        print(f"- `{m}`" + ("  (exe root)" if m in t["exe_roots"] else ""))
    print()
    print(f"### Test files importing tooling modules: {len(r['tests_importing_tooling'])}\n")
    for m, hits in sorted(r["tests_importing_tooling"].items()):
        print(f"- `{m}` -> " + ", ".join(f"`{h}`" for h in hits))
    print()
    print("Pruned from the walk: " + ", ".join(f"`{m}`" for m in r["pruned_roots"] if not m.startswith(LIB + ".Examples."))
          + f" and every module under `{LIB}.Examples`.\n")


# ---------------------------------------------------------------------------
# namespace-audit
# ---------------------------------------------------------------------------

def classify_namespace(dir_module, ns):
    """Compare a file's first namespace with its *directory* module.

    `Syntax/Formula.lean` has directory module `FormalSystem.Syntax`; a
    namespace equal to that, or below it, is the Mathlib-usual shape
    ("equal-or-descendant").  A namespace strictly above it ("ancestor") is
    Mathlib-acceptable.  Anything else is "unrelated" -- the file lives
    somewhere its namespace does not say.
    """
    if ns is None:
        return "none"
    if ns == dir_module or ns.startswith(dir_module + "."):
        return "equal-or-descendant"
    if dir_module.startswith(ns + "."):
        return "ancestor"
    return "unrelated"


def measure_namespaces(g):
    buckets = {"equal-or-descendant": [], "ancestor": [], "unrelated": [], "none": []}
    for m, p in g.modules.items():
        if not m.startswith(LIB + "."):
            continue
        ns = first_namespace(p)
        dir_module = m.rsplit(".", 1)[0]
        buckets[classify_namespace(dir_module, ns)].append((m, ns))
    return {k: {"count": len(v), "entries": sorted(v, key=lambda x: x[0])} for k, v in buckets.items()}


def print_namespaces(r):
    print("## Namespace audit (first `namespace` vs directory module, library files only)\n")
    print(md_table(["Bucket", "Files"], [(k, v["count"]) for k, v in r.items()]))
    print()
    print("### Unrelated\n")
    print(md_table(["Module", "First namespace"], [(f"`{m}`", f"`{ns}`") for m, ns in r["unrelated"]["entries"]]))
    print()


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

MODES = {
    "upward-edges": (measure_upward_edges, print_upward_edges),
    "weakcanonical-partition": (measure_weakcanonical, print_weakcanonical),
    "automation-partition": (measure_automation, print_automation),
    "namespace-audit": (measure_namespaces, print_namespaces),
}


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0],
                                 formatter_class=argparse.RawDescriptionHelpFormatter,
                                 epilog="\n".join(__doc__.split("\n\n")[1:]))
    ap.add_argument("mode", nargs="?", choices=sorted(MODES) + ["all"],
                    help="which measurement to print (default: all, or none with --check)")
    ap.add_argument("--json", action="store_true", help="emit JSON instead of markdown")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the Expressiveness set has any edge into the residual "
                         "WeakCanonical set or into BXCanonical")
    args = ap.parse_args(argv)
    if not os.path.isdir(LIB):
        print(f"measure-refactor-partitions.py: no {LIB}/ directory; run from the repository root",
              file=sys.stderr)
        return 2

    g = ImportGraph()
    modes = list(MODES) if args.mode in (None, "all") else [args.mode]
    if args.check and args.mode is None:
        modes = []

    results = {m: MODES[m][0](g) for m in modes}
    if args.json:
        print(json.dumps(results, indent=2))
    else:
        for m in modes:
            MODES[m][1](results[m])

    if args.check:
        r = results.get("weakcanonical-partition") or measure_weakcanonical(g)
        bad = r["leaking_edges"]
        not_free = r["expressiveness_not_bx_free"]
        if bad or not_free:
            print(f"FAIL  Expressiveness set leaks: {len(bad)} edge(s) into residual/BXCanonical, "
                  f"{len(not_free)} module(s) reach BXCanonical by closure")
            for s, t in bad:
                print(f"      {s} -> {t}")
            for m in not_free:
                print(f"      closure: {m}")
            return 1
        print(f"PASS  Expressiveness set ({r['expressiveness']['files']} files) has no edge into the "
              f"residual WeakCanonical set ({r['residual']['files']} files) or BXCanonical")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
