#!/usr/bin/env python3
"""Measure the structural partitions the publication refactor programme depends on.

Every number in ``docs/development/PUBLICATION_REFACTOR.md`` and in ADR-011 is
regenerated by this script, never typed.  It reads the live tree through
``scripts/lib/import_graph.py`` (leading-import parse, archive excluded by
directory name) and prints markdown tables, or JSON with ``--json``.

Usage (run from the repository root):

  measure-refactor-partitions.py upward-edges
  measure-refactor-partitions.py weakcanonical-partition
  measure-refactor-partitions.py automation-partition
  measure-refactor-partitions.py namespace-audit
  measure-refactor-partitions.py all
  measure-refactor-partitions.py --check      # exit 1 if the Expressiveness set leaks

The four measurements:

  upward-edges             Every import that runs *up* the layer stack recorded
                           in ORGANISATION.md (Syntax/ProofSystem/ForMathlib/
                           Init/Tactic/Version=0, Semantics=1, Theorems=2,
                           Metalogic/Automation=3, Examples/MainResults=4, and
                           the three language directories per file at 0, 1 or
                           3), grouped by source and target directory, with the
                           Theorems <-> Metalogic pair and any stale per-file
                           row called out.
  weakcanonical-partition  Each module under Metalogic/WeakCanonical/ classified
                           by whether BXCanonical is in its transitive closure;
                           the proposed Expressiveness set (EXPRESSIVENESS_SET
                           below) with its file and line counts, the residual
                           set, and every edge from the Expressiveness set into
                           the residual or into BXCanonical (expected: none).
  automation-partition     The Automation modules the *library* needs -- the
                           union of the closures of every non-Automation
                           library module, with Examples/, MainResults and the
                           tooling-only TraceExport pruned from the walk --
                           against the complement, which is dataset/ML tooling.
  namespace-audit          Each live file's first `namespace` against its
                           module path: equal-or-descendant, ancestor, unrelated
                           or none.

``--check`` is the pre-move gate for the Expressiveness extraction: it exits 0
only when the Expressiveness set has no edge into the residual WeakCanonical
set and none into BXCanonical.  Never weaken it; if it fails, the offending
edges are the work, and the relocation has to be dependency-first.

Measured on the tree as it stands after the language directories were layered:
  upward-edges              7 import lines in total, one class, MinusLanguage ->
                            Theorems: MinusLanguage/AxiomDischarge.lean (layer 0)
                            importing 7 Theorems modules (layer 2).  0 into
                            Automation from any of the four acceptance source
                            directories (Syntax, Semantics, ProofSystem,
                            Theorems); 0 Theorems files import Metalogic; 29
                            Metalogic files import Theorems; 0 stale per-file
                            rows.  scripts/check-metalogic-cycles.sh asserts
                            that the upward set EQUALS its recorded 7-line
                            allowlist.
                            The three language directories (MinusLanguage/,
                            PlusLanguage/, StarLanguage/) are layered PER FILE
                            by LANGUAGE_FILE_LAYERS below, keyed on each file's
                            directory before the language-extension merge: 13
                            files at layer 0, 16 at layer 1, 1 at layer 3.  One
                            layer L for all three directories was measured and
                            rejected -- it leaves 23 upward lines at L=0, 9 at
                            L=1, 5 at L=2 and 3 at L=3, a set that tracks the
                            number chosen rather than the tree.  layer_of
                            raises UnlayeredModuleError for any module under
                            FormalSystem/ that matches no row; it returns None
                            only for the bare root and for non-library modules.
  weakcanonical-partition   Expressiveness 141 files / 104,087 lines,
                            residual 38 files / 28,498 lines, 0 leaking edges;
                            BXCanonical-free by closure: 150 of 179
  automation-partition      9 library-needed modules (3,419 lines), 4
                            user-facing tactic modules (1,238), 25 tooling
                            modules including TraceExport (14,747)
  namespace-audit           8 unrelated, every one a recorded exception whose
                            own module docstring explains it: ForMathlib PFilter
                            (namespace Order.PFilter, Mathlib's own, kept for
                            upstreaming); Theorems.DeductionTheorem (namespace
                            Metalogic.Core); Tactic.Meta (namespace Automation);
                            Semantics.FrameClassValidity (namespace
                            ProofSystem, required by dot notation on
                            FrameClass); Decidability.BiLasso.Periodic
                            (namespace ...Decidability.Periodic, a deliberately
                            directory-independent scheme); and the three
                            Chronicle files.  The 15 {Plus,Minus,Star}Language
                            files that used to sit here left the bucket when
                            the merge gave each language one root-level
                            directory and renamed the semantics namespaces to
                            match.

For the tree the programme was originally written against (commit 220e94ea4),
upward-edges reported 16 lines from the then-five lower layers into Automation,
11 of them into the attribute-only files TruthNormAttr and LemmaDB, and 4
Theorems files importing Metalogic.Core.DeductionTheorem.  Those three attribute
modules no longer exist -- their five declarations were merged into
FormalSystem/Tactic/Attr.lean, which Init.lean imports, and all 11 lines were
deleted outright -- and DeductionTheorem.lean now lives under Theorems/.

Where a document and this output disagree, this output is right; the document
records the discrepancy rather than the other way round.
"""

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "lib"))
from import_graph import ImportGraph, first_namespace  # noqa: E402

LIB = "FormalSystem"

# ORGANISATION.md's layer table, keyed by the first path component below `FormalSystem/`.
# EVERY module under `FormalSystem/` has a layer: a directory through its row here, the two
# root-level single files `Version` (0: it imports only `Init`) and `MainResults`
# (4: it audits every headline theorem, so it sits with Examples at the top) through their own
# rows, and a file in one of the three language directories through LANGUAGE_FILE_LAYERS below.
# A module that matches no row is an ERROR, not a module "with no layer" -- see `layer_of`.
# Only the bare root `FormalSystem` (it imports everything by construction) and modules outside
# the library have no layer.
#
# This is the MEASURED order, not an aspirational one.  Two entries are
# load-bearing and are easy to get wrong:
#
#   * `Tactic: 0`.  Without it `layer_of` returns None for every `Tactic` module
#     and the directory contributes no edge in either direction, so the layer-0
#     placement of the attribute declarations would be invisible here.
#   * `Theorems` (2) strictly BELOW `Metalogic` (3), and `Automation` (3) BESIDE
#     `Metalogic` rather than above it.  Both follow the measurement: 50 Metalogic
#     modules import Theorems and none of the reverse remains, and the surviving
#     `Decidability -> {ProofSearch, Normalization}` lines are library automation
#     called from the decision procedure, which is an intra-layer edge, not an
#     upward one.  See ORGANISATION.md, which states the same table in prose.
LAYERS = {
    "Syntax": 0, "ProofSystem": 0, "ForMathlib": 0, "Init": 0, "Tactic": 0, "Version": 0,
    "Semantics": 1,
    "Theorems": 2,
    "Metalogic": 3,
    "Automation": 3,
    "Examples": 4, "MainResults": 4,
}

# The three language directories hold a language's syntax, proof system AND semantics in one
# directory, so no single layer number describes them.  That is measured, not argued: giving all
# three directories one layer L yields a non-empty upward set for every L (the figures are in
# this script's module docstring and in ORGANISATION.md), and the set that survives reflects the
# number chosen rather than the tree.  So each FILE carries its own layer.
#
# THE RULE IS THE FILE'S PRE-MERGE ORIGIN DIRECTORY, not a judgement about its content.  The
# language-extension merge (commit e2b646c84) moved every one of these files out of a directory
# that already had a layer; `git show -M --name-status e2b646c84` is the table's source:
#
#   from Syntax/<Lang>/                      -> 0
#   from Semantics/<Lang>/                   -> 1
#   from Metalogic/Conservativity/           -> 3   (`MinusLanguage/Soundness.lean` only; it
#                                                    imports two Metalogic modules)
#
# A file created AFTER the merge (everything under `OpenLanguage/`) has no origin directory; it
# takes the layer of the directory it would have occupied before the merge: a syntax file
# (`Syntax/<Lang>/`) takes 0, a semantic file (`Semantics/<Lang>/`) takes 1 -- which is what
# assertion C of scripts/check-metalogic-cycles.sh already enforces.
#
# A content judgement is deliberately NOT the rule.  It could file `AxiomDischarge` -- whose 7
# imports of `Theorems` are the whole measured upward set -- at layer 2 and empty the allowlist
# in scripts/check-metalogic-cycles.sh by assertion.  That allowlist once emptied because these
# directories stopped being measured; reclassifying the file would reach the same blind spot by
# another route.  The 7 lines are recorded, not excused.
#
# AN EXPLICIT TABLE, NOT A FILENAME HEURISTIC.  Every layer-1 file happens to carry its
# language's name as a prefix (`PlusTruth`, `MinusFrame`) and every unprefixed file is layer 0 --
# except `Soundness`, which is layer 3.  A prefix rule would be right for all files but that one
# and would classify the NEXT new file silently, which is the failure this table exists to
# prevent.  A new file in a language directory needs a row here; without one `layer_of` raises.
# A row whose file has gone is reported as stale (`stale_language_rows`) and fails assertion B
# of check-metalogic-cycles.sh, so the table cannot drift in either direction.
LANGUAGE_FILE_LAYERS = {
    "MinusLanguage": {
        "AxiomDischarge": 0, "Axioms": 0, "Derivation": 0, "Formula": 0, "Translation": 0,
        "MinusFrame": 1, "MinusSchemaValidity": 1, "MinusTruth": 1, "MinusValidity": 1,
        "Soundness": 3,
    },
    "PlusLanguage": {
        "Axioms": 0, "Derivation": 0, "Formula": 0, "Substitution": 0,
        "PlusDeterminism": 1, "PlusLimitClosure": 1, "PlusNonValidities": 1, "PlusPasting": 1,
        "PlusStateLocal": 1, "PlusTruth": 1, "PlusValidity": 1,
    },
    "StarLanguage": {
        "Axioms": 0, "Derivation": 0, "Embedding": 0, "Formula": 0,
        "StarDeterminism": 1, "StarNonValidities": 1, "StarStateLocal": 1, "StarTruth": 1,
        "StarValidity": 1,
    },
    "OpenLanguage": {
        "OpenClasses": 1,
    },
}

# The sibling aggregators `FormalSystem/<Lang>Language.lean` import their directory's layer-0 and
# layer-1 files, so they take the higher of the two as a DECLARED layer.  (`MinusLanguage.lean`
# does not import `Soundness` and cannot: `Soundness` reaches the aggregator through
# `Metalogic.Conservativity.Backward`.)  This matters here and not in check-metalogic-cycles.sh:
# that script excludes sibling aggregators as edge sources, `measure_upward_edges` does not.
LANGUAGE_AGGREGATOR_LAYER = 1

WEAK = f"{LIB}.Metalogic.WeakCanonical"
EXPR = f"{LIB}.Metalogic.Expressiveness"
BX = f"{LIB}.Metalogic.BXCanonical"

# The Metalogic/Expressiveness/ set, named relative to EXPR.  A name is a subtree
# (every module below it) or a single module.  Before the extraction these names
# were relative to WeakCanonical/ and the subtree now called `GameTransfer` was
# called `Expressiveness`; both roots are read from their post-move locations.
EXPRESSIVENESS_SET = (
    "Kamp", "EFGames", "GameTransfer", "Separation",
    "NormalForm", "MonadicFO", "StaviConnectives",
    "PriorDefs", "PriorDefsDense", "PriorExpressiveness", "PriorExpressivenessDense",
    "Table", "EFGameTactics",
)

# User-facing tactic modules: library API that no library file imports (a user
# does), so the closure walk cannot see them.  Classified as library, not tooling.
USER_FACING_TACTICS = frozenset(
    f"{LIB}.Automation.Tactics.{n}" for n in ("Commands", "Deduction", "Search", "UserTactics")
)

# Pruned from the automation-partition walk: these import Automation on purpose
# (Examples imports the whole aggregator; MainResults audits everything;
# TraceExport is tooling whose only consumer is an exe root).
AUTOMATION_PRUNE_PREFIXES = (f"{LIB}.Examples",)
AUTOMATION_PRUNE_MODULES = (
    f"{LIB}.Examples",
    f"{LIB}.MainResults",
    f"{LIB}.Metalogic.Decidability.TraceExport",
    f"{LIB}.Automation",          # the aggregator imports every Automation module
    f"{LIB}.FormalSystem",        # the two roots import the aggregator
    LIB,
)


def top_dir(module):
    parts = module.split(".")
    return parts[1] if len(parts) > 1 and parts[0] == LIB else None


class UnlayeredModuleError(LookupError):
    """A module under ``FormalSystem/`` that matches no row of any layer table.

    Raised rather than answered with ``None``: a ``None`` layer drops every import into and out
    of the module from the upward-edge measurement without a word, which is how the three
    language directories went unmeasured.
    """

    def __init__(self, module, table, missing_row):
        self.module, self.table, self.missing_row = module, table, missing_row
        super().__init__(
            f"no layer for `{module}`: {table} in scripts/measure-refactor-partitions.py has no "
            f"row `{missing_row}`. Add the row (and the matching line of ORGANISATION.md's layer "
            f"table); an unlayered module is invisible to the upward-edge measurement.")


def layer_of(module):
    """The layer of a library module, or ``None`` for a module that is not in the library.

    ``None`` is returned ONLY when the first component is not ``FormalSystem`` (Mathlib, the
    test library, ...) or the module is the bare root ``FormalSystem``.  Every other module
    either matches a row or raises ``UnlayeredModuleError`` naming the table that lacks it.
    """
    parts = module.split(".")
    if parts[0] != LIB or len(parts) == 1:
        return None
    d = parts[1]
    if d in LANGUAGE_FILE_LAYERS:
        if len(parts) == 2:
            return LANGUAGE_AGGREGATOR_LAYER
        # The key is the dotted path below the language directory, so a module nested deeper
        # than one level has no row either until someone writes one for it explicitly.
        leaf = ".".join(parts[2:])
        if leaf not in LANGUAGE_FILE_LAYERS[d]:
            raise UnlayeredModuleError(module, f'the per-file table LANGUAGE_FILE_LAYERS["{d}"]', leaf)
        return LANGUAGE_FILE_LAYERS[d][leaf]
    if d not in LAYERS:
        raise UnlayeredModuleError(module, "the top-level table LAYERS", d)
    return LAYERS[d]


def stale_language_rows(g):
    """Rows of LANGUAGE_FILE_LAYERS whose module is not in the import graph.

    The other direction of drift from the one ``layer_of`` raises on: a file was renamed,
    moved or deleted and its row stayed behind.
    """
    return sorted(f"{LIB}.{d}.{leaf}" for d, rows in LANGUAGE_FILE_LAYERS.items()
                  for leaf in rows if f"{LIB}.{d}.{leaf}" not in g.modules)


def md_table(headers, rows):
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# upward-edges
# ---------------------------------------------------------------------------

def measure_upward_edges(g):
    lib_modules = [m for m in g.modules if m.startswith(LIB + ".")]
    edges = []  # (src_module, tgt_module)
    for src in lib_modules:
        ls = layer_of(src)
        if ls is None:
            continue
        for tgt in g.edges[src]:
            lt = layer_of(tgt)
            if lt is None or lt <= ls:
                continue
            edges.append((src, tgt))
    classes = {}
    for src, tgt in edges:
        classes.setdefault((top_dir(src), top_dir(tgt)), []).append((src, tgt))
    # The four ACCEPTANCE source directories -- Syntax, Semantics, ProofSystem,
    # Theorems -- are all strictly below Automation (3) in the table above, so an
    # import line from any of them into Automation is visible in `edges` and is
    # counted here.  `Metalogic` is BESIDE Automation, so a Metalogic -> Automation
    # line is intra-layer, absent from `edges`, and therefore uncounted; it stays
    # in this tuple so that a future table change that moves Metalogic back down
    # starts counting those lines again instead of silently dropping them.
    #
    # DO NOT "simplify" this by deriving the source set from LAYERS.  Reading the
    # acceptance directories off an already layer-filtered list is exactly how a
    # renumber -- moving Automation beside Theorems, say -- could make a quarter of
    # the acceptance criterion read zero without a single file moving.
    into_automation = [(s, t) for s, t in edges if top_dir(t) == "Automation"
                       and top_dir(s) in ("Syntax", "Semantics", "ProofSystem", "Theorems", "Metalogic")]
    # Both directions of the Theorems <-> Metalogic pair are computed directly
    # rather than read off `edges`.  The table puts Theorems (2) below Metalogic
    # (3), so Metalogic -> Theorems is the DOWNWARD direction and is invisible in
    # `edges`, while Theorems -> Metalogic is what `edges` would show.  That
    # asymmetry is the opposite way round from the table this script carried
    # before the relocation, which is exactly why both directions are computed
    # here rather than being read off a list whose contents flip with a renumber.
    theorems_to_metalogic = sorted({s for s in lib_modules if top_dir(s) == "Theorems"
                                    for t in g.edges[s] if top_dir(t) == "Metalogic"})
    metalogic_to_theorems = sorted({s for s in lib_modules if top_dir(s) == "Metalogic"
                                    for t in g.edges[s] if top_dir(t) == "Theorems"})
    return {
        "edge_count": len(edges),
        "into_automation_line_count": len(into_automation),
        "classes": {f"{a} -> {b}": sorted(v) for (a, b), v in sorted(classes.items())},
        "theorems_files_importing_metalogic": theorems_to_metalogic,
        "metalogic_files_importing_theorems": metalogic_to_theorems,
        "stale_language_rows": stale_language_rows(g),
    }


def print_upward_edges(r):
    print("## Upward edges (source layer below target layer per ORGANISATION.md)\n")
    print(f"Total upward import lines: {r['edge_count']} "
          f"({r['into_automation_line_count']} from the four acceptance source "
          f"directories plus Metalogic into Automation)\n")
    for cls, pairs in r["classes"].items():
        print(f"### {cls} ({len(pairs)} lines)\n")
        print(md_table(["Source module", "Imports"], pairs))
        print()
    print(f"### Theorems <-> Metalogic\n")
    print(f"- Theorems files importing Metalogic: {len(r['theorems_files_importing_metalogic'])}")
    for m in r["theorems_files_importing_metalogic"]:
        print(f"  - `{m}`")
    print(f"- Metalogic files importing Theorems: {len(r['metalogic_files_importing_theorems'])}")
    print()
    print(f"### Stale per-file rows (LANGUAGE_FILE_LAYERS rows with no file): "
          f"{len(r['stale_language_rows'])}\n")
    for m in r["stale_language_rows"]:
        print(f"- `{m}`")
    if r["stale_language_rows"]:
        print()


# ---------------------------------------------------------------------------
# weakcanonical-partition
# ---------------------------------------------------------------------------

def subtree_head(module):
    """The EXPRESSIVENESS_SET member a moved module belongs to."""
    return module[len(EXPR) + 1:].split(".")[0]


def measure_weakcanonical(g):
    # The two sets live under two roots since the extraction: the moved set under
    # EXPR, the residual set under WEAK.  Reading both from WEAK (as this script
    # did before the move) would make the moved set silently empty and every
    # assertion below vacuously true -- see the empty-set guard in the --check
    # branch, which exists to make that failure mode loud.
    expr_members = g.under(EXPR)
    weak_members = g.under(WEAK)
    expr_agg = EXPR if EXPR in expr_members else None
    aggregator = WEAK if WEAK in weak_members else None
    expr = sorted(m for m in expr_members if m != EXPR)
    resid = sorted(m for m in weak_members if m != WEAK)
    modules = expr + resid
    expr_set, resid_set = set(expr), set(resid)

    def bx_free(m):
        return not any(c == BX or c.startswith(BX + ".") for c in g.closure(m))

    pure = sorted(m for m in modules if bx_free(m))
    impure = sorted(m for m in modules if m not in set(pure))

    leaks = []
    for m in expr:
        for t in g.edges[m]:
            if t in resid_set or t == BX or t.startswith(BX + "."):
                leaks.append((m, t))
    importers_outside = {}
    for m in expr:
        for src in g.reverse.get(m, ()):
            if src not in expr_set:
                importers_outside.setdefault(src, []).append(m)

    def lines(ms):
        return sum(g.line_count(m) for m in ms)

    subtree_rows = []
    for name in EXPRESSIVENESS_SET:
        ms = [m for m in expr if subtree_head(m) == name]
        subtree_rows.append((name, len(ms), lines(ms)))

    return {
        "aggregator": aggregator,
        "expressiveness_aggregator": expr_agg,
        "module_count": len(modules),
        "expressiveness": {"files": len(expr), "lines": lines(expr), "modules": expr,
                           "subtrees": subtree_rows},
        "residual": {"files": len(resid), "lines": lines(resid), "modules": resid},
        "bxcanonical_free_by_closure": {"pure": len(pure), "impure": len(impure),
                                        "impure_modules": impure},
        "expressiveness_not_bx_free": sorted(m for m in expr if m not in set(pure)),
        "leaking_edges": leaks,
        "importers_outside_set": {k: sorted(v) for k, v in sorted(importers_outside.items())},
    }


def print_weakcanonical(r):
    e, s = r["expressiveness"], r["residual"]
    print("## WeakCanonical partition\n")
    print(f"Modules under `Metalogic/Expressiveness/` and `Metalogic/WeakCanonical/`: {r['module_count']}"
          + (f" (plus the sibling aggregator `{r['aggregator']}`, not counted)" if r["aggregator"] else "") + "\n")
    print(md_table(["Set", "Files", "Lines"],
                   [("Expressiveness", e["files"], f"{e['lines']:,}"),
                    ("Residual WeakCanonical", s["files"], f"{s['lines']:,}")]))
    print()
    print("### Expressiveness set by subtree\n")
    print(md_table(["Name (relative to Expressiveness/)", "Files", "Lines"],
                   [(n, f, f"{l:,}") for n, f, l in e["subtrees"]]))
    print()
    p = r["bxcanonical_free_by_closure"]
    print(f"BXCanonical-free by transitive closure: {p['pure']} of {r['module_count']} "
          f"({p['impure']} reach BXCanonical)\n")
    if r["expressiveness_not_bx_free"]:
        print("Expressiveness modules that reach BXCanonical (MUST be empty):")
        for m in r["expressiveness_not_bx_free"]:
            print(f"- `{m}`")
        print()
    print(f"### Edges from the Expressiveness set into the residual set or BXCanonical: "
          f"{len(r['leaking_edges'])}\n")
    for src, tgt in r["leaking_edges"]:
        print(f"- `{src}` -> `{tgt}`")
    if r["leaking_edges"]:
        print()
    print("### Importers of the Expressiveness set from outside it\n")
    for src, tgts in r["importers_outside_set"].items():
        print(f"- `{src}` ({len(tgts)} line{'s' if len(tgts) != 1 else ''})")
    print()
    print("### Residual modules\n")
    for m in s["modules"]:
        print(f"- `{m}`")
    print()


# ---------------------------------------------------------------------------
# automation-partition
# ---------------------------------------------------------------------------

def measure_automation(g):
    auto_prefix = f"{LIB}.Automation."
    automation = sorted(m for m in g.modules if m.startswith(auto_prefix))
    prune = set(AUTOMATION_PRUNE_MODULES) | {
        m for m in g.modules if any(m == p or m.startswith(p + ".") for p in AUTOMATION_PRUNE_PREFIXES)
    }
    roots = [m for m in g.modules
             if m.startswith(LIB + ".") and not m.startswith(auto_prefix) and m not in prune]
    needed = set()
    needed_by = {}
    for r in roots:
        for c in g.closure(r, exclude=frozenset(prune)):
            if c.startswith(auto_prefix):
                needed.add(c)
                # record direct importers only, for the table
        for t in g.edges[r]:
            if t.startswith(auto_prefix):
                needed_by.setdefault(t, set()).add(r)
    needed = sorted(needed)
    user_facing = sorted(m for m in automation if m in USER_FACING_TACTICS)
    tooling = sorted(m for m in automation if m not in set(needed) and m not in USER_FACING_TACTICS)
    # TraceExport is tooling that never lived under Automation/, so the walk above cannot find
    # it; it is added by hand. GUARDED ON EXISTENCE, and that guard is load-bearing rather than
    # defensive: once the module is relocated out of `FormalSystem.` this append would otherwise
    # put a phantom row into a partition that is supposed to be empty, and the line-count pass
    # below would be counting a file that is no longer there.
    trace_export = f"{LIB}.Metalogic.Decidability.TraceExport"
    if trace_export in g.modules:
        tooling.append(trace_export)
    tooling.sort()
    exe_roots = sorted(m for m in tooling if m.endswith("Main"))
    tests_importing_tooling = {}
    for m in g.modules:
        if not m.startswith("BimodalTest"):
            continue
        hits = [t for t in g.edges[m] if t in set(tooling)]
        if hits:
            tests_importing_tooling[m] = hits

    def lines(ms):
        return sum(g.line_count(m) for m in ms)

    return {
        "library_needed": {"count": len(needed), "lines": lines(needed), "modules": needed,
                           "direct_importers": {k: sorted(v) for k, v in sorted(needed_by.items())}},
        "user_facing_tactics": {"count": len(user_facing), "lines": lines(user_facing),
                                "modules": user_facing},
        "tooling": {"count": len(tooling), "lines": lines(tooling), "modules": tooling,
                    "exe_roots": exe_roots},
        "tests_importing_tooling": tests_importing_tooling,
        "pruned_roots": sorted(prune & set(g.modules)),
    }


def print_automation(r):
    n, u, t = r["library_needed"], r["user_facing_tactics"], r["tooling"]
    print("## Automation partition\n")
    print(md_table(["Set", "Modules", "Lines"],
                   [("Library-needed Automation modules (by closure)", n["count"], f"{n['lines']:,}"),
                    ("User-facing tactic modules (library API, imported by no library file)",
                     u["count"], f"{u['lines']:,}"),
                    ("Tooling (dataset / ML / benchmark / exe roots, plus TraceExport)",
                     t["count"], f"{t['lines']:,}")]))
    print()
    print("### Library-needed modules and their direct importers outside Automation\n")
    rows = []
    for m in n["modules"]:
        imps = n["direct_importers"].get(m, [])
        rows.append((f"`{m}`", len(imps), ", ".join(f"`{i}`" for i in imps[:4]) + (" ..." if len(imps) > 4 else "")))
    print(md_table(["Module", "Direct importers", "Examples"], rows))
    print()
    print("### Tooling modules\n")
    for m in t["modules"]:
        print(f"- `{m}`" + ("  (exe root)" if m in t["exe_roots"] else ""))
    print()
    print(f"### Test files importing tooling modules: {len(r['tests_importing_tooling'])}\n")
    for m, hits in sorted(r["tests_importing_tooling"].items()):
        print(f"- `{m}` -> " + ", ".join(f"`{h}`" for h in hits))
    print()
    print("Pruned from the walk: " + ", ".join(f"`{m}`" for m in r["pruned_roots"] if not m.startswith(LIB + ".Examples."))
          + f" and every module under `{LIB}.Examples`.\n")


# ---------------------------------------------------------------------------
# namespace-audit
# ---------------------------------------------------------------------------

def classify_namespace(dir_module, ns):
    """Compare a file's first namespace with its *directory* module.

    `Syntax/Formula.lean` has directory module `FormalSystem.Syntax`; a
    namespace equal to that, or below it, is the Mathlib-usual shape
    ("equal-or-descendant").  A namespace strictly above it ("ancestor") is
    Mathlib-acceptable.  Anything else is "unrelated" -- the file lives
    somewhere its namespace does not say.
    """
    if ns is None:
        return "none"
    if ns == dir_module or ns.startswith(dir_module + "."):
        return "equal-or-descendant"
    if dir_module.startswith(ns + "."):
        return "ancestor"
    return "unrelated"


def measure_namespaces(g):
    buckets = {"equal-or-descendant": [], "ancestor": [], "unrelated": [], "none": []}
    for m, p in g.modules.items():
        if not m.startswith(LIB + "."):
            continue
        ns = first_namespace(p)
        dir_module = m.rsplit(".", 1)[0]
        buckets[classify_namespace(dir_module, ns)].append((m, ns))
    return {k: {"count": len(v), "entries": sorted(v, key=lambda x: x[0])} for k, v in buckets.items()}


def print_namespaces(r):
    print("## Namespace audit (first `namespace` vs directory module, library files only)\n")
    print(md_table(["Bucket", "Files"], [(k, v["count"]) for k, v in r.items()]))
    print()
    print("### Unrelated\n")
    print(md_table(["Module", "First namespace"], [(f"`{m}`", f"`{ns}`") for m, ns in r["unrelated"]["entries"]]))
    print()


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

MODES = {
    "upward-edges": (measure_upward_edges, print_upward_edges),
    "weakcanonical-partition": (measure_weakcanonical, print_weakcanonical),
    "automation-partition": (measure_automation, print_automation),
    "namespace-audit": (measure_namespaces, print_namespaces),
}


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0],
                                 formatter_class=argparse.RawDescriptionHelpFormatter,
                                 epilog="\n".join(__doc__.split("\n\n")[1:]))
    ap.add_argument("mode", nargs="?", choices=sorted(MODES) + ["all"],
                    help="which measurement to print (default: all, or none with --check)")
    ap.add_argument("--json", action="store_true", help="emit JSON instead of markdown")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the Expressiveness set has any edge into the residual "
                         "WeakCanonical set or into BXCanonical")
    args = ap.parse_args(argv)
    if not os.path.isdir(LIB):
        print(f"measure-refactor-partitions.py: no {LIB}/ directory; run from the repository root",
              file=sys.stderr)
        return 2

    g = ImportGraph()
    modes = list(MODES) if args.mode in (None, "all") else [args.mode]
    if args.check and args.mode is None:
        modes = []

    try:
        results = {m: MODES[m][0](g) for m in modes}
    except UnlayeredModuleError as e:
        print(f"measure-refactor-partitions.py: {e}", file=sys.stderr)
        return 1
    if args.json:
        print(json.dumps(results, indent=2))
    else:
        for m in modes:
            MODES[m][1](results[m])

    if args.check:
        r = results.get("weakcanonical-partition") or measure_weakcanonical(g)
        bad = r["leaking_edges"]
        not_free = r["expressiveness_not_bx_free"]
        # An empty Expressiveness set makes every assertion below vacuously true.
        # ADR-011 promises this check is "a standing pre-move gate"; without this
        # branch it would degenerate to a permanent PASS the moment either root
        # stopped resolving.  Fail loudly instead.
        if not r["expressiveness"]["files"] or not r["residual"]["files"]:
            print(f"FAIL  degenerate partition: Expressiveness set has "
                  f"{r['expressiveness']['files']} file(s) and the residual WeakCanonical set has "
                  f"{r['residual']['files']} file(s); neither may be empty.")
            print(f"      Expressiveness root: {EXPR}")
            print(f"      residual root:       {WEAK}")
            print("      An empty set makes the leak assertion vacuous. Re-point the roots "
                  "rather than accepting the PASS.")
            return 1
        if bad or not_free:
            print(f"FAIL  Expressiveness set leaks: {len(bad)} edge(s) into residual/BXCanonical, "
                  f"{len(not_free)} module(s) reach BXCanonical by closure")
            for s, t in bad:
                print(f"      {s} -> {t}")
            for m in not_free:
                print(f"      closure: {m}")
            return 1
        print(f"PASS  Expressiveness set ({r['expressiveness']['files']} files) has no edge into the "
              f"residual WeakCanonical set ({r['residual']['files']} files) or BXCanonical")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
