#!/usr/bin/env python3
"""
Dataset Metadata Standardization

Enriches existing metadata files with common header fields (dataset_name, version,
description, generation_date, schema_version) while preserving all existing fields
including the accurate representations array in c5/c7 metadata.

Usage:
    python scripts/standardize_metadata.py

Inputs/Outputs:
    data/bmlogic-c5_metadata.json  - ENRICHED in-place with common header fields
    data/bmlogic-c7_metadata.json  - ENRICHED in-place with common header fields

The script reads each metadata file, adds missing common header fields, and writes
back with consistent JSON formatting (sorted keys, 2-space indent).
"""

import json
import os
import shutil
from datetime import datetime

# ============================================================================
# Common header fields to add if not already present
# ============================================================================

DATASET_CONFIGS = {
    "data/bmlogic-c5_metadata.json": {
        "dataset_name": "bmlogic-c5",
        "version": "1.0.0",
        "description": (
            "Exhaustive bimodal logic training dataset at complexity 5. "
            "Generated by lake exe dataset_generator with --mode exhaustive and --include-duals. "
            "Contains all bimodal formulas up to complexity 5 with S5 modal and linear temporal semantics. "
            "Supersedes bmlogic-medium.jsonl from Task 213."
        ),
        "generation_date": "2026-05-29",
        "schema_version": "2.0",
        "license": "MIT",
        "task_origin": "Task 213",
    },
    "data/bmlogic-c7_metadata.json": {
        "dataset_name": "bmlogic-c7",
        "version": "1.0.0",
        "description": (
            "Exhaustive bimodal logic training dataset at complexity 7. "
            "Generated by lake exe dataset_generator with --mode exhaustive and --include-duals. "
            "Contains all bimodal formulas up to complexity 7 with S5 modal and linear temporal semantics. "
            "Supersedes bmlogic-deep.jsonl from Task 213."
        ),
        "generation_date": "2026-05-29",
        "schema_version": "2.0",
        "license": "MIT",
        "task_origin": "Task 213",
    },
}

# Common header field order (these appear first in the output)
HEADER_FIELDS = [
    "dataset_name",
    "version",
    "description",
    "generation_date",
    "schema_version",
    "license",
    "task_origin",
]


def enrich_metadata(path: str, additions: dict) -> dict:
    """
    Read a metadata file, add missing common header fields, and return enriched dict.

    Preserves all existing fields. Only adds fields that are not already present.
    """
    with open(path) as f:
        existing = json.load(f)

    # Add header fields that don't already exist
    for key, value in additions.items():
        if key not in existing:
            existing[key] = value

    return existing


def ordered_metadata(data: dict) -> dict:
    """
    Return metadata dict with header fields first, then remaining fields sorted.

    This produces consistent, human-readable JSON output.
    """
    result = {}

    # First: header fields in defined order (only if present)
    for field in HEADER_FIELDS:
        if field in data:
            result[field] = data[field]

    # Then: remaining fields in sorted order
    for key in sorted(data.keys()):
        if key not in HEADER_FIELDS:
            result[key] = data[key]

    return result


def process_metadata_file(path: str, additions: dict) -> None:
    """Back up, enrich, and write back a metadata file."""
    print(f"Processing: {path}")

    # Back up original
    backup_path = path + ".bak"
    shutil.copy2(path, backup_path)
    print(f"  Backed up to: {backup_path}")

    # Enrich
    enriched = enrich_metadata(path, additions)
    ordered = ordered_metadata(enriched)

    # Write back
    with open(path, "w") as f:
        json.dump(ordered, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"  Enriched with {len(additions)} common header fields")
    print(f"  Total fields: {len(ordered)}")

    # Validate round-trip
    with open(path) as f:
        reloaded = json.load(f)
    assert reloaded == ordered, "Round-trip validation failed!"
    print(f"  JSON validation: OK")

    # Remove backup on success
    os.remove(backup_path)
    print(f"  Backup removed.")
    print()


def main():
    print("Dataset Metadata Standardization")
    print("=" * 40)
    print()

    for path, additions in DATASET_CONFIGS.items():
        if not os.path.exists(path):
            print(f"WARNING: {path} not found, skipping")
            continue
        process_metadata_file(path, additions)

    print("All metadata files standardized successfully.")


if __name__ == "__main__":
    main()
