#!/usr/bin/env python3
"""Build-free compiler-warning ratchet for the BimodalLogic tree.

`lake build` exits 0 while emitting compiler warnings, and C16 (Batteries `env_linter` via
`lake exe runLinter`) is a *declaration* linter that never sees them -- the two sets are
disjoint. This script closes that hole: it measures the all-target compiler-warning surface
from Lake's own trace store and compares it against a committed baseline, so a change that
adds a warning must edit the baseline and say why.

It is deliberately BUILD-FREE. CI invokes `bash scripts/check-module-invariants.sh --no-build`,
and docs/development/CI_CD_PROCESS.md records that C2/C6/C24 are consequently not run in CI at
all. A gate that shelled out to `lake build` would silently join that list. Instead the
acquisition walks `.lake/build/lib/lean/**/*.trace`, which Lake writes per module and replays on
a cache hit -- the same replay that makes `lake build --wfail` fail on a warm cache.

NEVER regenerate scripts/warning-budget.txt to make a genuine regression disappear. `--update`
rewrites the file wholesale from current counts and would bless the regression along with
everything else, exactly the failure mode C16's header warns about for scripts/nolints.json.
The recorded counts are a CEILING and may only decrease. To retire a warning, fix it and let
`--update` show the count dropping in the same commit as the fix, with the diff visible.

Baseline key: `<count> <path> <linter>`. Deliberately not a per-class scalar (which cannot catch
one warning fixed and another introduced in the same class), and deliberately without line
numbers (so ordinary edits above a warning do not churn the baseline).

Usage (run from the repository root):
  warning-budget.py                verify observed counts against the baseline (default)
  warning-budget.py --list         current counts, highest first
  warning-budget.py --update       rewrite the baseline from current counts
  warning-budget.py --from-build   re-derive the same numbers from all-target build stdout,
                                   schema-independently (for re-baselining and after a
                                   toolchain bump); reads stdin, or --build-log FILE

Options:
  --root DIR          repository root (default: the script's parent's parent)
  --trace-dir DIR     override the trace store location
  --build-log FILE    with --from-build, read this file instead of stdin
  --filter SUBSTR     with --list, restrict output to paths containing SUBSTR

THE TRACE STORE MUST BE QUIESCENT. Do not run this while a `lake build` is in flight: a build
rewrites `.lake/build/lib/lean/**/*.trace` as it goes, so a concurrent read can see a module's
trace half-written or already invalidated and report a count that is wrong. Observed in practice
as a spurious `FAIL C28 ... above baseline` that reproduced zero times once the build had
finished. The error is always in the SAFE direction -- a partially-read store loses warnings from
the BASELINE side of the comparison, never invents tolerance -- so it can produce a false FAIL
but not a false PASS. CI is unaffected because lean-action completes before the `--no-build`
invariants step runs. If a local run fails and a build was running, re-run it once the build is
done before looking for a regression.

Exit status:
  0  verified (or a successful --list/--update)
  1  a count exceeds its baseline entry, or a path/linter pair is absent from the baseline
  2  usage or environment error, INCLUDING every anti-silence and undispositioned-class guard.
     A measurement this script cannot trust is an error in every mode and is never suppressed
     by ENFORCE_C28=0 -- silence must never read as success.
"""

import argparse
import json
import os
import re
import sys
from collections import Counter

BASELINE_NAME = "scripts/warning-budget.txt"
TRACE_GLOB_ROOT = ".lake/build/lib/lean"

# Position prefix Lean puts on every diagnostic: `<path>:<line>:<col>: `.
POS_RE = re.compile(r"^([^\s:]+\.lean):(\d+):(\d+): ")
# The `Note: This linter can be disabled with `set_option linter.X false`` trailer.
LINTER_RE = re.compile(r"set_option (linter\.[A-Za-z0-9_]+) false")

DISPOSITIONS = ("blocking", "advisory", "pending")

HEADER = """\
# Compiler-warning budget -- the committed baseline for C28.
#
# Generated by scripts/warning-budget.py. Each entry is `<count> <path> <linter>`.
#
# THE COUNTS ARE A CEILING AND MAY ONLY DECREASE. Never regenerate this file to make a
# genuine regression disappear: `--update` rewrites it wholesale from current findings and
# would bless the regression along with everything else -- the same failure mode C16's header
# warns about for scripts/nolints.json. To retire a warning, fix it and let the count drop in
# the same commit as the fix, with the `--update` diff visible in that commit.
#
# Every linter class observed in the tree MUST have a disposition row below. A class with no
# row is exit 2, not a silent pass -- that guard is what stops a future linter class being
# absorbed into this baseline by a routine `--update` without anyone reading it.
#
# Dispositions: blocking | advisory | pending
#   blocking  a warning of this class fails the gate
#   advisory  counted and reported, does not fail the gate
#   pending   NOT YET ANALYSED -- the gate cannot ship enforced while any row reads pending
"""


def die(msg: str) -> "None":
    print(f"warning-budget.py: {msg}", file=sys.stderr)
    raise SystemExit(2)


def classify(message: str) -> str:
    """Name the linter class responsible for one warning message."""
    m = LINTER_RE.search(message)
    if m:
        return m.group(1)
    if "has been deprecated" in message:
        return "deprecated"
    if "Try this: intro" in message:
        return "introMerge"
    return "UNCLASSIFIED"


def scan_traces(root: str, trace_dir: str) -> "tuple[Counter, int, int]":
    """Walk the Lake trace store. Returns (counts, n_traces, n_stale)."""
    counts: Counter = Counter()
    n_traces = 0
    n_logged = 0
    n_stale = 0
    unclassified = []
    for dirpath, _dirnames, filenames in os.walk(trace_dir):
        for fn in filenames:
            if not fn.endswith(".trace"):
                continue
            n_traces += 1
            path = os.path.join(dirpath, fn)
            try:
                with open(path, "rb") as fh:
                    data = json.load(fh)
            except (OSError, json.JSONDecodeError):
                continue
            if not isinstance(data, dict):
                continue
            log = data.get("log")
            if log is None:
                continue
            n_logged += 1
            for entry in log:
                if not isinstance(entry, dict) or entry.get("level") != "warning":
                    continue
                message = entry.get("message", "")
                m = POS_RE.match(message)
                if not m:
                    # A warning with no source position is not attributable to a file and
                    # cannot be baselined per path. Surface it rather than dropping it.
                    unclassified.append(("<no-position>", message[:200]))
                    continue
                src = m.group(1)
                if not os.path.exists(os.path.join(root, src)):
                    # Stale trace for a deleted or renamed source file.
                    n_stale += 1
                    continue
                klass = classify(message)
                if klass == "UNCLASSIFIED":
                    unclassified.append((src, message[:200]))
                    continue
                counts[(src, klass)] += 1

    # Anti-silence guard 1: no trace files at all means the measurement is vacuous.
    if n_traces == 0:
        die(
            f"no *.trace files under {trace_dir} -- the warning surface cannot be measured. "
            "Build the tree first; an unmeasurable surface is an error, never a pass."
        )
    # Anti-silence guard 2: traces exist but none carries a `log` key, so either the schema
    # changed or these are not compilation traces. Either way the scan proves nothing.
    if n_logged == 0:
        die(
            f"{n_traces} trace file(s) under {trace_dir} but not one carries a `log` key -- "
            "the trace schema has probably changed. Re-derive with --from-build and re-baseline."
        )
    if unclassified:
        lines = "\n".join(f"    {p}: {msg}" for p, msg in unclassified[:10])
        die(
            f"{len(unclassified)} warning(s) match no known class (linter note, deprecation, "
            f"or introMerge):\n{lines}\n"
            "UNCLASSIFIED is an error, not a silent bucket -- extend classify()."
        )
    return counts, n_traces, n_stale


BUILD_WARN_RE = re.compile(r"^warning: ([^\s:]+\.lean):(\d+):(\d+): (.*)$")


def scan_build_log(text: str, root: str) -> Counter:
    """Re-derive the same counts from all-target `lake build` stdout, schema-independently.

    Lake prints each diagnostic as `warning: <path>:<line>:<col>: <message>` followed by any
    continuation lines (the `Note: This linter can be disabled ...` trailer among them) until
    the next `warning:`/`error:`/`info:` banner or a Lake progress line.
    """
    counts: Counter = Counter()
    cur = None  # (src, [message lines])
    banner = re.compile(r"^(warning|error|info): ")
    progress = re.compile(r"^(✓|✗|ℹ|\[\d+/\d+\]|Build completed|error: )")

    def flush() -> None:
        nonlocal cur
        if cur is None:
            return
        src, lines = cur
        klass = classify("\n".join(lines))
        if klass != "UNCLASSIFIED" and os.path.exists(os.path.join(root, src)):
            counts[(src, klass)] += 1
        cur = None

    for line in text.splitlines():
        m = BUILD_WARN_RE.match(line)
        if m:
            flush()
            cur = (m.group(1), [m.group(4)])
            continue
        if banner.match(line) or progress.match(line):
            flush()
            continue
        if cur is not None:
            cur[1].append(line)
    flush()
    return counts


def parse_baseline(path: str) -> "tuple[dict, dict, dict]":
    """Returns (entries, dispositions, per-entry reasons).

    A `#` comment line directly above an entry is that entry's reason, following the same
    convention scripts/debug-artifact-allowlist.txt uses for C27. Every NON-ZERO entry must
    carry one: a residual warning nobody explained is indistinguishable from one nobody noticed,
    and absorbing warnings silently is the exact failure this ratchet exists to prevent.
    """
    entries: dict = {}
    disp: dict = {}
    reasons: dict = {}
    prev_comment = None
    try:
        with open(path, encoding="utf-8") as fh:
            raw = fh.read()
    except OSError as e:
        die(f"cannot read {path}: {e}")
    for n, line in enumerate(raw.splitlines(), 1):
        s = line.strip()
        if s.startswith("# disposition "):
            parts = s[len("# disposition ") :].split(None, 2)
            if len(parts) < 2 or parts[1] not in DISPOSITIONS:
                die(
                    f"{path}:{n}: malformed disposition row `{s}` "
                    f"(want `# disposition <linter> <{'|'.join(DISPOSITIONS)}> <reason>`)"
                )
            disp[parts[0]] = (parts[1], parts[2] if len(parts) > 2 else "")
            continue
        if not s:
            prev_comment = None
            continue
        if s.startswith("#"):
            prev_comment = s.lstrip("#").strip()
            continue
        parts = s.split()
        if len(parts) != 3 or not parts[0].isdigit():
            die(f"{path}:{n}: malformed entry `{s}` (want `<count> <path> <linter>`)")
        entries[(parts[1], parts[2])] = int(parts[0])
        if prev_comment:
            reasons[(parts[1], parts[2])] = prev_comment
        prev_comment = None
    return entries, disp, reasons


def render(counts: Counter, disp: dict, reasons: "dict | None" = None) -> str:
    out = [HEADER]
    for klass in sorted(disp):
        value, reason = disp[klass]
        out.append(f"# disposition {klass} {value} {reason}".rstrip())
    total = sum(counts.values())
    files = len({p for p, _ in counts})
    out.append("#")
    out.append(f"# Baseline total: {total} warning(s) across {files} file(s).")
    out.append("")
    reasons = reasons or {}
    for (p, k), c in sorted(counts.items()):
        r = reasons.get((p, k))
        if r:
            out.append(f"# {r}")
        out.append(f"{c} {p} {k}")
        if r:
            out.append("")
    return "\n".join(out) + "\n"


# Seed dispositions, used only when the baseline file does not yet exist.
SEED_DISPOSITIONS = {
    "deprecated": ("blocking", "forward-compat debt; becomes a build error at the next bump"),
    "linter.unusedSimpArgs": ("blocking", "dead simp argument; safe to delete (no `<-` caveat in tree)"),
    "linter.unusedSectionVars": ("blocking", "fix per declaration with the `omit [...] in` form Lean prints"),
    "linter.unusedVariables": ("blocking", "rename to a `_`-prefixed binder; do not delete (arity)"),
    "linter.unusedTactic": ("blocking", "fix or document via declaration-scoped `set_option ... in`"),
    "linter.unreachableTactic": ("blocking", "fix or document via declaration-scoped `set_option ... in`"),
    "introMerge": ("advisory", "style suggestion; fixed where it reads better, tolerated where not"),
    "linter.defProp": ("pending", "NOT YET ANALYSED - the test-library read sets this row"),
}


def main(argv: "list[str]") -> int:
    here = os.path.dirname(os.path.abspath(__file__))
    default_root = os.path.dirname(here)
    ap = argparse.ArgumentParser(add_help=True, description=__doc__)
    ap.add_argument("--root", default=default_root)
    ap.add_argument("--trace-dir", default=None)
    ap.add_argument("--build-log", default=None)
    ap.add_argument("--filter", default=None)
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--list", action="store_true")
    mode.add_argument("--update", action="store_true")
    mode.add_argument("--from-build", action="store_true")
    try:
        args = ap.parse_args(argv)
    except SystemExit:
        return 2

    root = os.path.abspath(args.root)
    trace_dir = args.trace_dir or os.path.join(root, TRACE_GLOB_ROOT)
    baseline_path = os.path.join(root, BASELINE_NAME)

    if args.from_build:
        if args.build_log:
            try:
                with open(args.build_log, encoding="utf-8", errors="replace") as fh:
                    text = fh.read()
            except OSError as e:
                die(f"cannot read {args.build_log}: {e}")
        else:
            text = sys.stdin.read()
        if not text.strip():
            die("--from-build read an empty build log; pipe all-target `lake build` output in")
        counts = scan_build_log(text, root)
        total = sum(counts.values())
        by_class: Counter = Counter()
        for (_p, k), c in counts.items():
            by_class[k] += c
        print(f"warning-budget (--from-build): {total} warning(s) across "
              f"{len({p for p, _ in counts})} file(s)")
        for k, c in by_class.most_common():
            print(f"  {c:5d}  {k}")
        return 0

    counts, n_traces, n_stale = scan_traces(root, trace_dir)
    total = sum(counts.values())
    files = {p for p, _ in counts}

    if args.list:
        by_class: Counter = Counter()
        for (_p, k), c in counts.items():
            by_class[k] += c
        sel = {kv: c for kv, c in counts.items()
               if args.filter is None or args.filter in kv[0]}
        sel_total = sum(sel.values())
        print(f"warning-budget: {total} warning(s) across {len(files)} file(s) "
              f"({n_traces} traces, {n_stale} stale entr(y/ies) dropped)")
        if args.filter:
            print(f"  filter {args.filter!r}: {sel_total} warning(s) across "
                  f"{len({p for p, _ in sel})} file(s)")
        print("  by class:")
        for k, c in by_class.most_common():
            print(f"    {c:5d}  {k}")
        print("  by file:")
        per_file: Counter = Counter()
        for (p, _k), c in sel.items():
            per_file[p] += c
        for p, c in per_file.most_common():
            klasses = ", ".join(sorted(f"{k}:{sel[(p, k)]}" for (pp, k) in sel if pp == p))
            print(f"    {c:5d}  {p}  [{klasses}]")
        return 0

    observed_classes = {k for _p, k in counts}

    if args.update:
        _old_entries, disp, reasons = ({}, dict(SEED_DISPOSITIONS), {})
        if os.path.exists(baseline_path):
            _old_entries, disp, reasons = parse_baseline(baseline_path)
            for k in observed_classes:
                disp.setdefault(k, SEED_DISPOSITIONS.get(
                    k, ("pending", "NOT YET ANALYSED - no disposition recorded")))
        missing = sorted(observed_classes - set(disp))
        if missing:
            die("observed linter class(es) with no disposition row: " + ", ".join(missing))
        with open(baseline_path, "w", encoding="utf-8") as fh:
            fh.write(render(counts, disp, reasons))
        print(f"warning-budget: wrote {baseline_path} -- {total} warning(s) across "
              f"{len(files)} file(s)")
        return 0

    # Default: verify.
    if not os.path.exists(baseline_path):
        die(f"{baseline_path} does not exist; run --update to create it")
    entries, disp, reasons = parse_baseline(baseline_path)

    # Anti-silence guard 3: a non-zero recorded baseline against a zero observation means the
    # scan is measuring nothing (wrong tree, wiped cache, changed schema) -- not that the
    # warnings were fixed. Passing here would be the silent-zero failure this gate exists to
    # prevent.
    if total == 0 and sum(entries.values()) > 0:
        die(
            f"observed 0 warnings but {baseline_path} records "
            f"{sum(entries.values())} -- refusing to pass on an untrustworthy measurement. "
            "Rebuild the tree, then re-run; if the warnings really are fixed, --update."
        )

    # Undispositioned-class guard: exit 2, never a silent pass.
    missing = sorted(observed_classes - set(disp))
    if missing:
        die(
            "observed linter class(es) with no disposition row in "
            f"{BASELINE_NAME}: {', '.join(missing)}. Read the class, decide "
            f"{'/'.join(DISPOSITIONS)}, and add a `# disposition` row -- do not absorb it "
            "into the baseline with a routine --update."
        )

    # `pending` marks a class nobody has read yet. It is explicitly temporary: the gate may not
    # ship enforced while any row still reads it. Enforced mechanically here rather than left to
    # a manual grep, because the grep form that suggests itself -- `grep -c pending <file>` --
    # can never reach 0: the file's own header legend has to explain what `pending` means, so the
    # bare word is always present and the check would pass vacuously forever. That is precisely
    # the silent-success failure this gate exists to prevent. The honest textual equivalent is
    # `grep -c '^# disposition .* pending ' scripts/warning-budget.txt`.
    pending = sorted(k for k in observed_classes
                     if disp.get(k, ("blocking", ""))[0] == "pending")
    if pending:
        die(
            "linter class(es) still marked `pending` in " + BASELINE_NAME + ": "
            + ", ".join(pending)
            + ". A pending class has not been read by anyone. Read it, decide blocking or "
            "advisory, and record the reason in its disposition row."
        )

    unexplained = sorted(k for k, v in entries.items() if v > 0 and not reasons.get(k))
    if unexplained:
        lines = "\n".join(f"    {p}  {k}  (baseline {entries[(p, k)]})" for p, k in unexplained)
        die(
            f"{len(unexplained)} non-zero baseline entr(y/ies) in {BASELINE_NAME} carry no "
            f"reason:\n{lines}\n"
            "Every warning this baseline tolerates must say WHY, on a `#` line directly above "
            "it, the same way scripts/debug-artifact-allowlist.txt does for C27. A residual "
            "warning nobody explained is indistinguishable from one nobody noticed."
        )

    failures = []
    for key, c in sorted(counts.items()):
        klass = key[1]
        if disp.get(klass, ("blocking", ""))[0] == "advisory":
            continue
        base = entries.get(key)
        if base is None:
            failures.append(f"  NEW    {c:5d}  {key[0]}  {klass}  (no baseline entry)")
        elif c > base:
            failures.append(f"  ABOVE  {c:5d}  {key[0]}  {klass}  (baseline {base})")

    if failures:
        print(f"warning-budget: FAIL -- {len(failures)} entr(y/ies) above baseline")
        for f in failures:
            print(f)
        print(f"\nThe counts in {BASELINE_NAME} are a ceiling and may only decrease. Fix the "
              "warning, or -- if it is genuinely acceptable -- run --update and justify the "
              "diff in the same commit.")
        return 1

    below = [(k, entries[k], counts.get(k, 0)) for k in entries
             if counts.get(k, 0) < entries[k]]
    print(f"warning-budget: OK -- {total} warning(s) across {len(files)} file(s), "
          f"all at or below baseline")
    if below:
        print(f"  {len(below)} entr(y/ies) now below baseline; run --update to ratchet down")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
